import {chromium} from '@playwright/test';import assert from 'node:assert/strict';import fs from 'node:fs/promises';
import {initialState,SAVE_KEY} from '../src/state.js';
const browser=await chromium.launch({headless:true,executablePath:'C:/Program Files/Google/Chrome/Application/chrome.exe'}),page=await browser.newPage({viewport:{width:1440,height:1000}}),errors=[],checks=[];
page.on('pageerror',e=>errors.push(e.message));page.on('response',r=>{if(r.url().includes('/assets/')&&r.status()>=400)errors.push(r.status()+' '+r.url());});
const read=()=>page.evaluate(()=>window.__roomTest.read().journey),view=()=>page.evaluate(()=>window.__roomTest.view()),shot=n=>page.screenshot({path:'test-results/journey-'+n+'.png'}),check=n=>{checks.push(n);console.log(n);};
async function focus(id){await page.evaluate(id=>window.__roomTest.focus(id),id);await page.waitForTimeout(250);await page.keyboard.press('KeyE');}
async function close(){await page.locator('#close-modal').click();}
async function code(text){await page.locator('#journey-code').fill(text);await page.locator('#journey-code-form button').click();}
async function waitZone(zone){await page.waitForFunction(zone=>window.__roomTest?.view().journey?.zone===zone&&!window.__roomTest.view().journey.transition,zone);await page.waitForTimeout(300);}
try{
 await page.goto('http://127.0.0.1:5179/?preview=journey&e2e=1');const original=await page.evaluate(k=>localStorage.getItem(k),SAVE_KEY);await page.locator('#princess-preview').click();await page.waitForFunction(()=>window.__roomTest?.view().mode==='journey',null,{timeout:90000});await shot('01-hell');check('New Blender scene loads with no asset failures');
 await focus('journey-phone');await shot('02-chat');await close();await focus('journey-lock');await code('wrong');assert.equal((await read()).freed,false);await code('china');await page.waitForTimeout(700);await shot('03-open-prison');await focus('journey-photo');await shot('04-photo');await close();await focus('journey-computer');await code('meaty');await shot('05-computer');check('Chat, wrong lock, china prison and meaty computer work through UI');
 await page.locator('#journey-open-camera').click();await page.evaluate(()=>window.__roomTest.look(0,1,2));await page.waitForTimeout(1500);assert.equal((await read()).ticket,false);await page.evaluate(()=>window.__roomTest.look(.7,1.69,-5.375));await page.waitForFunction(()=>window.__roomTest.read().journey.ticket);await shot('06-ticket');await close();check('Camera rejects wrong aim; steady alignment grants ICN–YNT / 2F / 6B');
 await focus('journey-up');await waitZone('church');assert.ok((await view()).position[1]>5.7);await shot('07-church');
 await page.evaluate(()=>{window.__roomTest.setPosition(2.5,-7);window.__roomTest.look(2.5,7.4,-10);});await page.keyboard.down('KeyW');await page.waitForTimeout(1100);await page.keyboard.up('KeyW');assert.equal((await read()).zone,'church');assert.ok((await view()).position[2]>-7.5);check('Closed boarding doors physically block entry before the meal');
 await focus('journey-pew-6A');assert.equal((await read()).bowl,false);await focus('journey-attendant');await page.locator('#journey-serve').click();assert.equal((await read()).served,false);await close();await focus('journey-pew-6B');await page.locator('#journey-take-bowl').click();await focus('journey-attendant');await page.locator('#journey-serve').click();await shot('08-happy-crew');await page.locator('#journey-serve').click();assert.equal((await read()).zone,'church');
 await page.evaluate(()=>window.__roomTest.focus('journey-board'));await page.waitForTimeout(1300);await shot('08b-open-gate');await page.keyboard.down('KeyW');await waitZone('plane');await page.keyboard.up('KeyW');await shot('09-first-class');check('Female crew opens the dedicated gate; player walks through the real aperture to board');
 await focus('journey-seat-2B');await page.locator('#journey-sit').click();await page.waitForTimeout(2200);await shot('10-flight');assert.equal((await read()).arrived,false);await page.keyboard.press('Escape');const f=(await read()).flight;await page.waitForTimeout(1100);assert.equal((await read()).flight,f);await close();await page.waitForFunction(()=>window.__roomTest.read().journey.arrived,null,{timeout:20000});assert.equal((await read()).flight,10);await focus('journey-land');await waitZone('restaurant');await shot('11-red-carpet');check('Freely chosen first class seat, paused timer and ten active seconds until arrival');
 await page.evaluate(()=>{window.__roomTest.look(50,1,0);});await page.keyboard.down('KeyW');await page.waitForTimeout(2800);await page.keyboard.up('KeyW');await shot('12-restaurant');await focus('journey-dine');await page.locator('[data-food="tofu"]').click();assert.deepEqual((await read()).chosen,[]);assert.ok((await read()).rejected.includes('tofu'));await shot('13-conveyor');for(const id of ['beef','watermelon','noodles','bokchoy','chicken']){await page.locator(`[data-food="${id}"]`).click();}assert.equal((await read()).satisfied,true);check('Moving conveyor rejects disliked food and accepts five distinct favorite dishes');
 await shot('14a-dinner');for(const beat of ['meal','offered','received','after-sip','sound','revealed','found']){await page.locator('#journey-tea-action').click();assert.equal(await page.locator('[data-story-beat]').getAttribute('data-story-beat'),beat);if(beat==='received')await shot('14-zagee');if(beat==='revealed')await shot('15-key-in-cup');}assert.equal((await read()).key,true);await page.locator('#journey-tea-action').click();await focus('journey-exit');await shot('16-complete');assert.equal((await read()).completed,true);assert.equal(await page.evaluate(k=>localStorage.getItem(k),SAVE_KEY),original);check('Shared meal, conversation, tea, sip, sound, inspection, key and day-500 threshold; preview preserves save');
 const complete=await page.evaluate(()=>window.__roomTest.read());await page.evaluate(({key,state})=>localStorage.setItem(key,JSON.stringify(state)),{key:SAVE_KEY,state:complete});await page.goto('http://127.0.0.1:5179/?e2e=1');await page.locator('#continue').click();await page.waitForFunction(()=>window.__roomTest?.view().mode==='journey',null,{timeout:90000});assert.equal((await read()).completed,true);check('Completed chapter restores through Continue');assert.deepEqual(errors,[]);await fs.writeFile('test-results/journey-report.json',JSON.stringify({ok:true,checks,errors,view:await view()},null,2));
}catch(e){await shot('failure');await fs.writeFile('test-results/journey-report.json',JSON.stringify({ok:false,checks,errors,error:e.stack,view:await view().catch(()=>null)},null,2));throw e;}finally{await browser.close();}
