import {chromium} from '@playwright/test';import assert from 'node:assert/strict';import fs from 'node:fs/promises';
import {initialState,SAVE_KEY} from '../src/state.js';import {initialBakery} from '../src/bakery-state.js';import {routeAnswer,ipadLetter} from '../src/junction-state.js';
const browser=await chromium.launch({headless:true,executablePath:'C:/Program Files/Google/Chrome/Application/chrome.exe'}),page=await browser.newPage({viewport:{width:1440,height:1000}}),errors=[],checks=[];
page.on('pageerror',e=>errors.push(e.message));page.on('response',r=>{if(r.url().includes('/assets/')&&r.status()>=400)errors.push(r.status()+' '+r.url());});
const read=()=>page.evaluate(()=>window.__roomTest.read()),view=()=>page.evaluate(()=>window.__roomTest.view()),shot=n=>page.screenshot({path:'test-results/junction-'+n+'.png'}),check=n=>{checks.push(n);console.log(n);};
async function ready(mode){await page.waitForFunction(mode=>window.__roomTest?.view().mode===mode,mode,{timeout:90000});await page.waitForTimeout(350);}
async function focus(id){await page.evaluate(id=>window.__roomTest.focus(id),id);await page.waitForTimeout(300);await page.keyboard.press('KeyE');}
async function close(){await page.locator('#close-modal').click();}
async function answer(v){await page.locator('#junction-answer').fill(v);await page.locator('#junction-answer-form button').click();}
async function resume(){await page.waitForFunction(()=>!document.querySelector('#continue').hidden&&typeof document.querySelector('#continue').onclick==='function');await page.locator('#continue').focus();await page.keyboard.press('Enter');}
try{
 await page.goto(new URL('?e2e=1',process.env.GAME_BASE_URL||'http://127.0.0.1:5179/').href);await page.evaluate(({key,s})=>localStorage.setItem(key,JSON.stringify(s)),{key:SAVE_KEY,s:{...initialState(),stage:8,completed:true,location:'bakery',bakery:initialBakery()}});await page.reload();await resume();await ready('bakery');await page.keyboard.press('KeyV');await page.mouse.wheel(0,700);assert.equal((await view()).thirdPerson,false);assert.equal(await page.locator('#view-btn').count(),0);await shot('00-expanded-bakery');await focus('bakery-order');assert.equal(await page.locator('#bakery-code').count(),0);await close();
 await focus('bakery-safe');await page.locator('#bakery-use-key').click();assert.equal((await read()).bakery.safeOpen,false);await close();
 await focus('bakery-register');await page.locator('#bakery-code').fill('92501');await page.locator('#bakery-code-form button[type=submit]').click();assert.equal((await read()).bakery.drawerOpen,false);await page.locator('#bakery-code').fill('92500');await page.locator('#bakery-code-form button[type=submit]').click();await page.waitForTimeout(1200);assert.equal((await read()).bakery.safeOpen,false);assert.ok((await view()).bakery.drawerZ>-2);await shot('01-drawer');await focus('bakery-key');await page.locator('#bakery-take-key').click();await focus('bakery-safe');await page.locator('#bakery-use-key').click();await page.waitForFunction(()=>window.__roomTest.view().bakery.safeAngle< -1.8);await shot('02-cake-lock');await focus('bakery-cake');await page.locator('#bakery-take-cake').click();assert.match(await page.locator('#modal-body').innerText(),/ㅋㅋ너가 이걸 참 맛있게 먹었었지/);for(let i=0;i<3;i++)await page.locator('#bakery-cake-action').click();await shot('03-usb');assert.equal((await read()).bakery.usbTaken,false);await page.locator('#bakery-cake-action').click();await page.waitForFunction(()=>window.__roomTest.view().bakery.gateAngle< -1.4);check('92500 opens only drawer; physical key opens cake; three bites reveal USB and unlock gate');
 await focus('bakery-letter');await page.locator('#bakery-take-letter').click();await focus('bakery-next');await page.locator('#bakery-enter-junction').click();await ready('junction');await shot('04-maze');assert.equal((await read()).location,'junction');check('Bakery USB door enters the POSTECH auditorium and saves chapter');
 await page.evaluate(()=>{window.__roomTest.setPosition(0,40);window.__roomTest.look(5,1.63,40);});await page.keyboard.down('KeyW');await page.waitForTimeout(1100);await page.keyboard.up('KeyW');const position=(await view()).position;assert.ok(position[0]<.8);check('Expanded maze perimeter blocks movement; collection routes are traversable');
 await focus('junction-blue');assert.equal(await page.locator('#modal-backdrop').isVisible(),false);assert.equal((await read()).junction.bluePowered,false);
 await focus('junction-red');await page.locator('#junction-insert-usb').click();await page.locator('[data-dir=U]').click();await page.locator('#junction-route-submit').click();assert.equal((await read()).junction.redPowered,false);await page.locator('#junction-route-reset').click();for(const d of routeAnswer)await page.locator(`[data-dir=${d}]`).click();await page.locator('#junction-route-submit').click();assert.match(await page.locator('#junction-red-line').innerText(),/팔랑귀/);await shot('05-red-lyric');await page.locator('[data-color=green]').click();assert.equal((await read()).junction.redPresses,0);
 for(let i=0;i<4;i++){const color=i<3?'red':'green';await page.locator(`[data-color=${color}]`).click();assert.equal((await read()).junction.redPresses,i*2+1);await page.locator(`[data-color=${color}]`).click();if(i<3)assert.equal((await read()).junction.redSolved,false);}assert.equal((await view()).junction.redBeam,true);await close();await shot('06-red-beam');check('Arrow sequence powers red; four separately displayed verses accept red2/red2/red2/green2');
 for(const id of ['victory','top'])await focus('junction-'+id);await focus('junction-bin');await page.locator('[data-trash=victory]').click();assert.equal((await read()).junction.bluePowered,false);await page.locator('[data-trash=top]').click();assert.equal((await read()).junction.bluePowered,true);await focus('junction-blue');await shot('07-blue-clue');await answer('8seconds');assert.equal((await read()).junction.coatSpawned,false);await answer('3seconds');await shot('08-coat');assert.equal((await read()).junction.blueSolved,false);await page.locator('#junction-take-coat').click();assert.equal((await view()).junction.blueBeam,true);check('Two distinct drink pickups and bin actions power blue; 3seconds releases +5 coat; lifting it activates blue beam');
 await focus('junction-yellow');await page.locator('#junction-offer').click();assert.equal((await read()).junction.offered,false);await close();for(let i=0;i<3;i++){await focus('junction-minion-'+i);assert.equal((await read()).junction.minions.length,i+1);}await shot('09-dolls');await focus('junction-yellow');await page.locator('#junction-offer').click();await answer('3seconds');assert.equal((await read()).junction.brandSolved,false);await answer('8seconds');assert.match(await page.locator('#modal-body').innerText(),/너는 항상 이 옷을 싫어했어/);await page.locator('#junction-go-hyunsu').click();check('Three dolls are required; wrong brand retains items; 8seconds reveals the clothing memory');
 await focus('junction-hyunsu');await page.locator('#junction-hyunsu-action').click();assert.equal((await read()).junction.dressed,true);await shot('10-dressed');await page.locator('#junction-hyunsu-action').click();assert.equal((await read()).junction.phase,'collapse');await page.waitForTimeout(1200);await page.keyboard.press('Escape');const frozen=(await read()).junction.phaseTime;await page.waitForTimeout(900);assert.equal((await read()).junction.phaseTime,frozen);await close();await page.waitForTimeout(3000);await shot('11-collapse-beams');await page.waitForFunction(()=>window.__roomTest.read().junction.phase==='tablet',null,{timeout:20000});assert.equal((await view()).junction.yellowBeam,true);assert.equal((await view()).junction.ipadVisible,true);await shot('12-ipad-arrival');check('Dressing then compliment starts a pausable collapse; three beams merge and iPad appears');
 await focus('junction-ipad');assert.equal(await page.locator('.junction-ipad p').innerText(),ipadLetter);await shot('13-ipad-letter');await page.locator('#junction-open-envelope').click();await page.locator('#junction-send-letter').click();assert.equal((await read()).junction.letterSent,false);const draft='현수야, 500일 축하해. 네가 가장 소중해.\n앞으로도 서로의 편이 되어 줄게. 사랑해!';await page.locator('#junction-letter').fill(draft);await page.reload();await resume();await ready('junction');assert.equal((await read()).junction.draft,draft);assert.equal(await page.locator('#junction-letter').inputValue(),draft);await close();await page.locator('#junction-letter-inventory').click();assert.equal(await page.locator('#junction-letter').inputValue(),draft);await shot('14-free-letter');await page.locator('#junction-send-letter').click();await page.waitForTimeout(5500);await shot('15-memory-returns');await page.waitForFunction(()=>window.__roomTest.read().junction.phase==='hearts',null,{timeout:25000});await page.waitForFunction(()=>window.__roomTest.read().junction.phaseTime>=5.5,null,{timeout:20000});await shot('16-hearts');const fp=await view();assert.equal(fp.thirdPerson,false);assert.ok(Math.abs(fp.camera[0]-fp.position[0])<.01);assert.ok(Math.abs(fp.camera[2]-fp.position[2])<.01);assert.ok(Math.abs(fp.camera[1]-fp.position[1]-1.63)<.02);assert.deepEqual((await view()).junction.hearts,[true,true]);await page.waitForFunction(()=>window.__roomTest.read().junction.completed,null,{timeout:15000});await shot('17-finale');assert.equal(await page.locator('#modal-title').innerText(),'500일 방탈출을 완료하였습니다');check('iPad text is exact; freeform draft survives reload; sending restores memory, guides both characters to circle and awards hearts');
 await page.reload();await resume();await ready('junction');await page.locator('#junction-prologue').waitFor();assert.equal((await read()).junction.completed,true);await page.locator('#junction-prologue').click();await page.locator('.film-start').waitFor();assert.equal(await page.locator('#memory-film').isVisible(),true);assert.equal(await page.evaluate(key=>JSON.parse(localStorage.getItem(key)).junction.completed,SAVE_KEY),true);check('Completed ending restores and Prologue button opens the photo film without deleting save');
 assert.deepEqual(errors,[]);await fs.writeFile('test-results/junction-report.json',JSON.stringify({ok:true,checks,errors},null,2));
}catch(e){await shot('failure');await fs.writeFile('test-results/junction-report.json',JSON.stringify({ok:false,checks,errors,error:e.stack,view:await view().catch(()=>null),state:await read().catch(()=>null)},null,2));throw e;}finally{await browser.close();}
