import test from 'node:test';import assert from 'node:assert/strict';
import {initialJunction,loadJunction,junctionTransition,routeAnswer,layout} from '../src/junction-state.js';
import {mazeCells,mazePoint,mazeWalls} from '../src/junction-world.js';
function player(){let s=initialJunction();return {get s(){return s;},act(e){const r=junctionTransition(s,e);assert.ok(r.ok,r.message);s=r.state;return s;},deny(e){const r=junctionTransition(s,e);assert.equal(r.ok,false);assert.equal(r.state,s);}};}
function red(p){p.act({type:'insert-usb'});p.act({type:'route',value:routeAnswer});for(const color of ['red','red','red','red','red','red','green','green'])p.act({type:'red-button',color});}
function blue(p){for(const id of ['victory','top']){p.act({type:'take-drink',id});p.act({type:'trash',id});}p.act({type:'seconds',value:'3seconds'});p.act({type:'take-coat'});}
function yellow(p){for(let id=0;id<3;id++)p.act({type:'minion',id});p.act({type:'offer'});p.act({type:'brand',value:'8seconds'});p.act({type:'dress'});p.act({type:'compliment'});}
function tick(p,seconds){for(let i=0;i<seconds*4;i++)p.act({type:'tick',dt:.25});}
test('maze shortest route matches the actual directional puzzle; every doll is reachable',()=>{const cells=mazeCells(),start=layout.route[0].join(','),goal=layout.route.at(-1).join(','),q=[[start,'']],seen=new Set([start]);let answer;while(q.length){const [k,path]=q.shift();if(k===goal){answer=path;break;}const [c,r]=k.split(',').map(Number);for(const [dx,dz,d]of [[0,-1,'U'],[1,0,'R'],[0,1,'D'],[-1,0,'L']]){const next=`${c+dx},${r+dz}`;if(cells.has(next)&&!seen.has(next)){seen.add(next);q.push([next,path+d]);}}}assert.equal(answer.replace(/(.)\1+/g,'$1'),routeAnswer);for(const p of layout.minions)assert.ok(cells.has(p.join(',')));});
test('red refuses bad route, reveals one line at a time, wrong colour resets only its pair',()=>{const p=player();p.deny({type:'route',value:routeAnswer});p.act({type:'insert-usb'});p.deny({type:'route',value:'UUUU'});p.act({type:'route',value:routeAnswer});p.act({type:'red-button',color:'red'});p.act({type:'red-button',color:'green'});assert.equal(p.s.redPresses,0);for(let i=0;i<6;i++)p.act({type:'red-button',color:'red'});assert.equal(p.s.redSolved,false);p.act({type:'red-button',color:'green'});p.act({type:'red-button',color:'green'});assert.equal(p.s.redSolved,true);});
test('strict colour order, real pickup and offering requirements, wrong answers preserve items',()=>{const p=player();for(const e of [{type:'take-drink',id:'top'},{type:'seconds',value:'3seconds'},{type:'offer'},{type:'brand',value:'8seconds'},{type:'dress'},{type:'compliment'}])p.deny(e);red(p);p.deny({type:'trash',id:'top'});for(const id of ['victory','top']){p.act({type:'take-drink',id});p.act({type:'trash',id});}p.deny({type:'seconds',value:'8seconds'});p.act({type:'seconds',value:'3 Seconds'});assert.equal(p.s.blueSolved,false);p.act({type:'take-coat'});p.deny({type:'offer'});for(let id=0;id<3;id++)p.act({type:'minion',id});p.deny({type:'minion',id:0});p.act({type:'offer'});p.deny({type:'brand',value:'3seconds'});assert.equal(p.s.minions.length,3);p.act({type:'brand',value:'8seconds'});p.deny({type:'compliment'});});
test('collapse, iPad, free letter, recovery, joining circle and hearts finish once and restore',()=>{const p=player();red(p);blue(p);yellow(p);assert.equal(p.s.phase,'collapse');tick(p,8);assert.equal(p.s.phase,'tablet');assert.equal(p.s.yellowSolved,true);p.act({type:'read-tablet'});p.act({type:'envelope'});p.deny({type:'send-letter'});const draft='현수야, 500일 축하해! <script>alert(1)</script>\n우리가 함께한 기억을 간직할게.';p.act({type:'draft',value:draft});assert.equal(loadJunction(p.s).draft,draft);p.act({type:'send-letter'});tick(p,8);assert.equal(p.s.phase,'walk');tick(p,7);assert.equal(p.s.phase,'hearts');tick(p,8);assert.equal(p.s.completed,true);assert.deepEqual(loadJunction(p.s),p.s);p.deny({type:'send-letter'});});
test('malformed and forged saves cannot unlock the ending',()=>{const s=loadJunction({...initialJunction(),redPresses:8,blueSolved:true,drinks:'oops',minions:[0,0,3],letterSent:true,completed:true,phase:'complete'});assert.equal(s.completed,false);assert.equal(s.blueSolved,false);assert.deepEqual(s.minions,[0]);});
