import test from 'node:test';
import assert from 'node:assert/strict';
import {initialKitchen,kitchenTransition,loadKitchen} from '../src/kitchen-state.js';
import {recipes,recipeKeys,employmentOrder} from '../src/kitchen-data.js';

const run=(state,event,now=20000)=>{const result=kitchenTransition(state,event,{now});assert.equal(result.ok,true,result.message);return result.state;};
const lit=()=>run(initialKitchen(),{type:'power',stations:employmentOrder});
const stocked=()=>{let state=lit();for(const recipe of Object.values(recipes))for(const step of recipe.steps)for(const item of step.need)state=run(state,{type:'take',item});return state;};
function finish(state,key){state=run(state,{type:'open',recipe:key});for(const step of recipes[key].steps){if(step.id==='order')state=run(state,{type:'order',recipe:key,brand:'BBQ',cut:'drumsticks',flavor:'half'},1000);else state=run(state,{type:'cook',recipe:key,action:step.id,heat:step.heat,amounts:[2,1,1,1,1],temperature:50});}return state;}

test('the four meals use the requested order and the first is kimchi fried rice',()=>{assert.deepEqual(recipeKeys,['kimchi','pepero','chili','chicken']);assert.match(recipes.kimchi.name,/김치볶음밥/);assert.match(recipes.chili.name,/칠리새우/);assert.equal('garlic' in recipes,false);});
test('darkness prevents shopping and opening rooms; correct subway memory lights them',()=>{const state=initialKitchen();for(const event of [{type:'take',item:'shrimp'},{type:'open',recipe:'kimchi'},{type:'power',stations:['상동','철산','신대방삼거리']}])assert.equal(kitchenTransition(state,event).ok,false);assert.equal(lit().lights,true);assert.equal(kitchenTransition(state,{type:'power',stations:employmentOrder},{order:null}).ok,false);});
test('doors unlock in order and a locked room cannot be cooked through',()=>{let state=stocked();assert.equal(kitchenTransition(state,{type:'open',recipe:'pepero'}).ok,false);assert.equal(kitchenTransition(state,{type:'cook',recipe:'kimchi',action:'chop'}).ok,false);state=finish(state,'kimchi');assert.equal(state.opened.kimchi,true);assert.equal(state.opened.pepero,false);state=loadKitchen(JSON.parse(JSON.stringify(state)));state=finish(state,'pepero');assert.equal(kitchenTransition(state,{type:'open',recipe:'chicken'}).ok,false);state=finish(state,'chili');state=finish(state,'chicken');assert.equal(state.completed,true);assert.deepEqual(state.bag,{});assert.deepEqual(loadKitchen(state),state);});
test('a failed step keeps ingredients and progress; cooking still checks heat and measurements',()=>{let state=stocked();state=run(state,{type:'open',recipe:'kimchi'});const before=structuredClone(state);assert.equal(kitchenTransition(state,{type:'cook',recipe:'kimchi',action:'plate'}).ok,false);assert.deepEqual(state,before);state=run(state,{type:'cook',recipe:'kimchi',action:'chop'});assert.equal(kitchenTransition(state,{type:'cook',recipe:'kimchi',action:'fry-kimchi',heat:'low'}).ok,false);for(const step of recipes.kimchi.steps.slice(state.progress.kimchi))state=run(state,{type:'cook',recipe:'kimchi',action:step.id,heat:step.heat});state=finish(state,'pepero');state=run(state,{type:'open',recipe:'chili'});for(const id of ['dry','garlic','shrimp']){const step=recipes.chili.steps.find(s=>s.id===id);state=run(state,{type:'cook',recipe:'chili',action:id,heat:step.heat});}assert.equal(kitchenTransition(state,{type:'cook',recipe:'chili',action:'measure',amounts:[1,1,1,1,1]}).ok,false);state=run(state,{type:'cook',recipe:'chili',action:'measure',amounts:[2,1,1,1,1]});assert.equal(state.bag.ketchup,undefined);});
test('chicken order requires the exact choice and the courier waits ten seconds',()=>{let state=stocked();for(const key of recipeKeys.slice(0,3))state=finish(state,key);state=run(state,{type:'open',recipe:'chicken'});assert.equal(kitchenTransition(state,{type:'order',recipe:'chicken',brand:'BBQ',cut:'whole',flavor:'half'}).ok,false);state=run(state,{type:'order',recipe:'chicken',brand:'BBQ',cut:'drumsticks',flavor:'half'},1000);state=loadKitchen(JSON.parse(JSON.stringify(state)));assert.equal(kitchenTransition(state,{type:'cook',recipe:'chicken',action:'receive'},{now:10999}).ok,false);state=run(state,{type:'cook',recipe:'chicken',action:'receive'},11000);assert.equal(state.received,true);});
test('unneeded store items can be returned without negative quantities',()=>{let state=lit();state=run(state,{type:'take',item:'broccoli'});state=run(state,{type:'return',item:'broccoli'});assert.equal(state.bag.broccoli,undefined);assert.equal(kitchenTransition(state,{type:'return',item:'broccoli'}).ok,false);});
