import {chromium} from '@playwright/test';import assert from 'node:assert/strict';import fs from 'node:fs/promises';
import {initialState,SAVE_KEY} from '../src/state.js';import {recipes,recipeKeys} from '../src/kitchen-data.js';import {initialKitchen} from '../src/kitchen-state.js';
const browser=await chromium.launch({headless:true,executablePath:'C:/Program Files/Google/Chrome/Application/chrome.exe'}),page=await browser.newPage({viewport:{width:1440,height:1000}}),errors=[],checks=[];
page.on('pageerror',e=>errors.push(e.message));page.on('response',r=>{if(r.url().includes('/assets/')&&r.status()>=400)errors.push(r.status()+' '+r.url());});
const check=s=>{checks.push(s);console.log(s);},read=()=>page.evaluate(()=>window.__roomTest.read()),view=()=>page.evaluate(()=>window.__roomTest.view()),shot=n=>page.screenshot({path:'test-results/rescue-'+n+'.png'});
async function focus(id){await page.evaluate(id=>window.__roomTest.focus(id),id);await page.waitForTimeout(150);await page.keyboard.press('KeyE');}
async function close(){await page.locator('#close-modal').click();}async function transition(){await page.waitForFunction(()=>!window.__roomTest.view().rescue?.transition);await page.waitForTimeout(500);}
async function startButton(id){await page.locator(id).focus();await page.keyboard.press('Enter');}
async function reload(){await page.reload();await startButton('#continue');await page.waitForFunction(()=>window.__roomTest?.view().mode==='rescue'&&window.__roomTest.view().rescue,null,{timeout:90000});await page.waitForTimeout(300);}
try{
 await page.goto('http://127.0.0.1:5179/?e2e=1');const cooking={...initialKitchen(),lights:true,completed:true,progress:Object.fromEntries(recipeKeys.map(k=>[k,recipes[k].steps.length]))};await page.evaluate(({key,state})=>localStorage.setItem(key,JSON.stringify(state)),{key:SAVE_KEY,state:{...initialState(),stage:8,completed:true,location:'kitchen',cooking}});await page.reload();await startButton('#continue');await page.waitForFunction(()=>window.__roomTest?.view().mode==='kitchen',null,{timeout:90000});await focus('kitchen-exit');await page.locator('#kitchen-finish').click();await page.waitForFunction(()=>window.__roomTest?.view().mode==='rescue',null,{timeout:90000});check('Completed kitchen leads into rescue chapter');await shot('01-sickroom');
 await focus('rescue-door-0');assert.equal((await read()).rescue.room,0);await focus('rescue-bed');await page.locator('#rescue-give').click();assert.equal((await read()).rescue.healed,false);await close();await focus('rescue-cabinet');await page.locator('#rescue-search').click();assert.equal((await read()).rescue.cabinetOpen,true);await shot('02-cabinet');await close();await page.waitForTimeout(1000);await shot('03-trophies');await focus('rescue-cabinet');await page.locator('#rescue-search').click();assert.equal((await read()).rescue.medicine,true);await reload();assert.equal((await read()).rescue.medicine,true);await focus('rescue-bed');await page.locator('#rescue-give').click();assert.equal((await read()).rescue.healed,true);check('Cabinet door, rummage and medication; held medicine survives reload');await focus('rescue-door-0');await transition();assert.equal((await read()).rescue.room,1);assert.ok(Math.abs((await view()).rescue.doors[0])<.2);await shot('04-boutique');
 await focus('rescue-cashier');await page.locator('#rescue-pay').click();assert.equal((await read()).rescue.paid.length,0);await close();await focus('rescue-rack');assert.equal(await page.locator('[data-garment]').count(),22);await page.locator('[data-garment="garment-83"]').click();await page.locator('[data-garment="polo-navy"]').click();await page.locator('[data-garment="tomboy-coat"]').click();assert.equal((await read()).rescue.selected.length,2);await shot('05-clothes');await page.locator('#rescue-leave-shop').click();await focus('rescue-cashier');await page.locator('#rescue-pay').click();await page.locator('#rescue-checkout-leave').click();await focus('rescue-cold');await page.locator('#rescue-give').click();assert.equal((await read()).rescue.warmed,false);assert.equal((await read()).rescue.paid.length,0);check('Exactly two garments; wrong purchase can be exchanged');
 await focus('rescue-rack');await page.locator('[data-garment="garment-83"]').click();await page.locator('[data-garment="tomboy-coat"]').click();await page.locator('#rescue-leave-shop').click();await focus('rescue-cashier');await page.locator('#rescue-pay').click();await shot('06-receipt');await page.locator('#rescue-checkout-leave').click();await reload();assert.equal((await read()).rescue.paid.length,2);await focus('rescue-cold');await page.locator('#rescue-give').click();assert.equal((await read()).rescue.warmed,true);await page.waitForTimeout(300);await shot('07-warm');check('Correct paid Polo/TOMBOY outfit is delivered and visibly worn');await focus('rescue-door-1');await transition();await shot('08-atlas-room');
 await focus('rescue-map');const pin=async(color,lon,lat)=>{await page.locator(`[data-pin="${color}"]`).click();const box=await page.locator('#rescue-map-surface').boundingBox();await page.mouse.click(box.x+(lon+180)/360*box.width,box.y+(90-lat)/180*box.height);};await pin('blue',-120,38);await pin('red',-52,-13);await page.locator('#rescue-board').click();assert.equal((await read()).rescue.board,false);await pin('blue',-99,31);await shot('09-map');assert.equal((await read()).rescue.pins.blue.region,'Texas');assert.equal((await read()).rescue.pins.red.region,'Brazil');await page.locator('#rescue-board').click();await reload();assert.equal((await read()).rescue.board,true);await focus('rescue-hungry');await page.locator('#rescue-give').click();assert.equal((await read()).rescue.fed,true);check('Real map coordinates reject California; Texas + Brazil creates physical proposal');
 await focus('rescue-door-2');await transition();assert.equal((await read()).rescue.quake,true);await shot('10-quake');await focus('rescue-door-3');assert.equal((await read()).rescue.completed,false);await focus('rescue-hand');assert.equal((await read()).rescue.holding,true);await page.evaluate(()=>window.__roomTest.look(42,1.5,1));await page.keyboard.down('KeyW');await page.waitForTimeout(650);await page.keyboard.up('KeyW');const before=await view();assert.ok(Math.abs(before.position[0]-before.rescue.npc[0])<1.3);await shot('11-holding');await reload();assert.equal((await read()).rescue.holding,true);check('Japanese quake alert; exit requires handholding; companion follows walking and reload');
 await focus('rescue-door-3');await transition();assert.equal((await read()).rescue.completed,true);assert.equal((await read()).rescue.room,4);await shot('12-safe');await focus('rescue-finish');await shot('13-complete');await page.locator('#rescue-rest').click();await reload();assert.equal((await read()).rescue.completed,true);check('Both reach day-400 room and all four rescue memories persist');
 await page.goto('http://127.0.0.1:5179/?preview=rescue&e2e=1');const persisted=await page.evaluate(key=>localStorage.getItem(key),SAVE_KEY);await startButton('#princess-preview');await page.waitForFunction(()=>window.__roomTest?.view().mode==='rescue');assert.equal((await read()).rescue.room,0);assert.equal(await page.evaluate(key=>localStorage.getItem(key),SAVE_KEY),persisted);check('Preview starts fresh without overwriting real progress');assert.deepEqual(errors,[]);await fs.writeFile('test-results/rescue-report.json',JSON.stringify({ok:true,checks,errors,view:await view()},null,2));
}catch(e){await shot('failure');await fs.writeFile('test-results/rescue-report.json',JSON.stringify({ok:false,checks,errors,error:e.stack,view:await view().catch(()=>null)},null,2));throw e;}finally{await browser.close();}
