import test from 'node:test';
import assert from 'node:assert/strict';
import {initialState,transition,loadState} from '../src/state.js';
const run=(s,e)=>{const r=transition(s,e);assert.equal(r.ok,true,r.message);return r.state;};
function through(stage){let s=initialState();const events=[{type:'read-letter'},{type:'lock',code:'VITA500'},{type:'frames',order:['yellow','green','blue','red']},{type:'give-violin',doll:'violinist'},{type:'take-carousel'},{type:'place-carousel'},{type:'take-bench'},{type:'place-bench',tile:9},{type:'place-beef',cut:'살치살'},{type:'taste',which:'hyunsu'},{type:'taste',which:'alpero'},{type:'vote',which:'hyunsu'},{type:'exit'}];for(const e of events){if(s.stage===stage)return s;s=run(s,e);}return s;}
test('all eight memories complete in order with consumed inventory',()=>{let s=through(8);assert.equal(s.stage,8);assert.equal(s.journal.length,8);assert.deepEqual(s.inventory,[]);assert.deepEqual(s.tasted,['hyunsu','alpero']);s=run(s,{type:'exit'});assert.equal(s.completed,true);});
test('a guessed lock is not accepted before reading the letter',()=>{const s=initialState(),r=transition(s,{type:'lock',code:'vita500'});assert.equal(r.ok,false);assert.deepEqual(r.state,s);});
test('incorrect frame sequence does not award a violin or consume progress',()=>{const s=through(1),r=transition(s,{type:'frames',order:['red','yellow','green','blue']});assert.equal(r.ok,false);assert.deepEqual(r.state,s);});
test('incorrect doll retains the unique violin, correct doll consumes it once',()=>{let s=through(2);assert.equal(transition(s,{type:'give-violin',doll:'bear'}).ok,false);assert.deepEqual(s.inventory,['violin']);s=run(s,{type:'give-violin',doll:'violinist'});assert.equal(s.stage,3);assert.deepEqual(s.inventory,[]);assert.equal(transition(s,{type:'give-violin',doll:'violinist'}).ok,false);});
test('incorrect floor position retains bench and retry succeeds',()=>{let s=run(through(5),{type:'take-bench'});assert.equal(transition(s,{type:'place-bench',tile:8}).ok,false);assert.ok(s.inventory.includes('bench'));s=run(s,{type:'place-bench',tile:9});assert.deepEqual(s.inventory,['beef']);assert.equal(s.stage,6);});
test('wrong cut never loses the beef token',()=>{let s=through(6);assert.equal(transition(s,{type:'place-beef',cut:'등심'}).ok,false);assert.deepEqual(s.inventory,['beef']);s=run(s,{type:'place-beef',cut:'살치살'});assert.equal(s.stage,7);});
test('voting needs two distinct tastings and Alpero can be retried',()=>{let s=through(7);s=run(s,{type:'taste',which:'hyunsu'});s=run(s,{type:'taste',which:'hyunsu'});assert.equal(s.tasted.length,1);assert.equal(transition(s,{type:'vote',which:'hyunsu'}).ok,false);s=run(s,{type:'taste',which:'alpero'});assert.equal(transition(s,{type:'vote',which:'alpero'}).ok,false);s=run(s,{type:'vote',which:'hyunsu'});assert.equal(s.stage,8);});
test('out-of-order interactions cannot skip puzzles',()=>{let s=initialState();for(const e of [{type:'frames',order:['yellow','green','blue','red']},{type:'take-carousel'},{type:'place-carousel'},{type:'place-bench',tile:9},{type:'place-beef',cut:'살치살'},{type:'vote',which:'hyunsu'},{type:'exit'}]){const r=transition(s,e);assert.equal(r.ok,false);assert.equal(r.state.stage,0);}});
test('saved progress survives reload and malformed saves are rejected',()=>{let s=through(6);assert.deepEqual(loadState(JSON.stringify(s)),s);for(const bad of ['{',null,'{}',JSON.stringify({...s,stage:99}),JSON.stringify({...s,inventory:'bad'}),JSON.stringify({...s,journal:[null]})])assert.equal(loadState(bad),null);});
