import {bakeryTransition,bakeryProducts,bakeryLetter,bakeryObjective} from './bakery-state.js';
const $=s=>document.querySelector(s);
export class BakeryController{
 constructor(api){Object.assign(this,api);}
 act(event){const r=bakeryTransition(this.getState(),event);if(!r.ok){this.sound.effect('error');this.toast(r.message);if($('#bakery-message'))$('#bakery-message').textContent=r.message;return false;}this.world.bakeryRuntime.sync(r.state);this.setState(r.state);this.sound.effect(r.effect);this.toast(r.message);return true;}
 modal(title,html){this.showModal('bakery','401 — 500 · 01 / DAEJEON',title,html+'<p id="bakery-message" class="puzzle-error" role="status" aria-live="polite"></p>');}
 interact(id){
  if(id==='bakery-order')return this.order();if(id==='bakery-register')return this.register();if(id==='bakery-key')return this.drawer();if(id==='bakery-safe'||id==='bakery-cake')return this.safe();if(id==='bakery-letter')return this.letter();if(id.startsWith('bakery-price-'))return this.price(id.slice(13));
  if(id==='bakery-next'){if(!this.getState().usbTaken)return this.toast('케이크 속에 남겨진 것을 먼저 챙겨 보자.');this.modal('다음 세계, 포스텍',`<div class="bakery-next-number">02</div><p class="body-copy">USB를 챙기자 문이 열렸다.<br>POSTECH 중앙강당 · JUNCTION KOREA 2026</p><button id="bakery-enter-junction" class="primary">열린 문으로 들어가기</button>`);$('#bakery-enter-junction').onclick=()=>this.onNext();}
 }
 order(){this.modal('계산을 기다리는 빵',`<p class="body-copy">“데스크 위에 올려둔 빵값을 모두 더해 주세요.”<br>합계를 구했다면 뒤쪽 계산대의 키패드에 입력해 줘.</p><ul class="bakery-order-list">${bakeryProducts.map(p=>`<li><span>${p.name}</span><strong>${p.quantity}개</strong></li>`).join('')}</ul><button id="bakery-close-order" class="primary">확인했어 · 계산대로 가기</button>`);$('#bakery-close-order').onclick=()=>this.closeModal();}
 price(id){const p=bakeryProducts.find(p=>p.id===id);if(!p)return;this.modal(p.name,`<div class="bakery-price"><small>개당 가격</small><strong>${p.price.toLocaleString('ko-KR')}<span>원</span></strong></div><p class="body-copy">판매 데스크에는 ${p.quantity}개.</p><button id="bakery-close" class="secondary">다른 빵도 살펴보기</button>`);$('#bakery-close').onclick=()=>this.closeModal();}
 drawer(){const s=this.getState();if(!s.drawerOpen)return this.toast('계산대 위 키패드에 비밀번호를 입력해 줘.');if(s.keyTaken)return this.toast('벽 쪽에 따로 놓인 망고시루 금고에 열쇠를 써 보자.');this.modal('서랍 속 작은 열쇠','<div class="bakery-cake-mark">🗝</div><p class="body-copy">열쇠의 꼬리표에 “망고시루”라고 적혀 있어.<br>벽 쪽의 망고시루 금고에 맞는 열쇠야.</p><button id="bakery-take-key" class="primary">열쇠 챙기기</button>');$('#bakery-take-key').onclick=()=>{if(this.act({type:'take-key'}))this.closeModal();};}
 register(){const s=this.getState();if(s.drawerOpen)return this.toast(s.keyTaken?'계산을 마쳤어. 벽 쪽 망고시루 금고로 가 보자.':'아래로 열린 서랍 안의 열쇠를 E로 챙겨 줘.');
  this.modal('계산대 · 비밀번호 입력',`<p class="body-copy">빵 데스크의 합계를 원 단위 다섯 자리로 입력하자.</p><form id="bakery-code-form"><label for="bakery-code">계산대 비밀번호</label><input id="bakery-code" class="bakery-code" inputmode="numeric" maxlength="5" pattern="[0-9]{5}" autocomplete="off" required><div class="bakery-keypad">${['1','2','3','4','5','6','7','8','9','지우기','0','←'].map(n=>`<button type="button" data-key="${n}">${n}</button>`).join('')}</div><button class="primary" type="submit">확인 · 서랍 열기</button></form>`);const input=$('#bakery-code');input.oninput=()=>input.value=input.value.replace(/\D/g,'').slice(0,5);document.querySelectorAll('[data-key]').forEach(b=>b.onclick=()=>{let k=b.dataset.key;input.value=k==='지우기'?'':k==='←'?input.value.slice(0,-1):(input.value+k).slice(0,5);input.focus();});$('#bakery-code-form').onsubmit=e=>{e.preventDefault();if(this.act({type:'unlock',code:input.value})){this.closeModal();this.subtitle('계산대 아래 서랍이 열렸다. 내려다보고 작은 열쇠를 챙기자.',6000);}};
 }
 safe(){const s=this.getState();if(!s.safeOpen){this.modal('잠긴 망고시루 보관함',`<p class="body-copy">망고시루는 열쇠로 잠긴 보관함 안에 있어.</p><button id="bakery-use-key" class="primary">${s.keyTaken?'서랍에서 찾은 열쇠 사용하기':'열쇠 구멍 살펴보기'}</button>`);$('#bakery-use-key').onclick=()=>{if(this.act({type:'open-cake'}))this.closeModal();};return;}if(s.cakeTaken)return this.cake();this.modal('보관함 속 망고시루','<div class="bakery-cake-mark">🥭</div><button id="bakery-take-cake" class="primary">망고시루 케이크 꺼내기</button>');$('#bakery-take-cake').onclick=()=>{if(this.act({type:'take-cake'}))this.cake();};}
 cake(){const s=this.getState();if(!s.cakeTaken)return this.safe();this.modal('망고시루 케이크',`<div class="bakery-cake-mark">${s.bites===3?'💾':'🥭'}</div><p class="body-copy">ㅋㅋ너가 이걸 참 맛있게 먹었었지</p><p class="body-copy">${s.bites===3?'케이크 속에서 USB가 나왔다!':`달콤한 망고와 크림 · ${s.bites} / 3입`}</p>${s.usbTaken?'<p class="body-copy">USB를 챙겼어. 포스텍으로 향하는 문이 열렸어.</p>':`<button id="bakery-cake-action" class="primary">${s.bites===3?'USB 챙기기':'맛있게 한 입 먹기'}</button>`}`);if($('#bakery-cake-action'))$('#bakery-cake-action').onclick=()=>{if(this.act({type:s.bites===3?'take-usb':'eat-cake'})){if(this.getState().usbTaken)this.closeModal();else this.cake();}};}
 letter(){const taken=this.getState().letterTaken;this.modal('찢어진 편지 조각',`<p class="body-copy">명란바게트 쟁반 아래 종이 귀퉁이가 있어.</p><article class="bakery-letter"><small>편지 조각 · 1 / 3</small><p>${bakeryLetter.text.replaceAll('\n','<br>')}</p></article><button id="bakery-take-letter" class="primary">${taken?'간직하기':'편지 1/3 조각 챙기기'}</button>`);$('#bakery-take-letter').onclick=()=>{if(taken||this.act({type:'take-letter'}))this.closeModal();};}
 hint(){this.modal('현수에게 물어보기',`<p class="body-copy">${bakeryObjective(this.getState())}</p><details><summary>힌트 펼치기</summary><p class="body-copy">데스크 위 빵만 계산해. 서랍의 열쇠는 망고시루 보관함에 맞아. 꺼낸 케이크도 끝까지 살펴봐.</p></details>`);}
}
