import {journeyTransition,journeyObjective,menu} from './journey-state.js';
import {journeyStory} from './journey-story.js';
import {ticketMarkup} from './journey-ticket.js';
import './journey-ticket.css';
import './journey-story.css';
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
const path='/assets/journey/';
export class JourneyController{
 constructor(api){Object.assign(this,api);this.world.journeyRuntime.onBoard=()=>{if(this.act({type:'board'}))this.closeModal();};this.lastSecond=-1;this.scanning=false;this.flightSave=0;if(!$('#journey-camera')){const el=document.createElement('div');el.id='journey-camera';el.hidden=true;el.innerHTML='<div class="camera-top">하영의 휴대폰 <b>카메라 · QR</b></div><div class="scan-frame"><i></i><i></i><i></i><i></i><span></span></div><p id="scan-copy">컴퓨터의 QR을 중앙 네모 안에 맞춰 줘.</p><div class="scan-meter"><i id="scan-meter-fill"></i></div><small>C · 카메라 닫기　 /　 마우스·방향키 · 조준</small>';document.body.append(el);const flight=document.createElement('aside');flight.id='journey-flight';flight.hidden=true;flight.setAttribute('role','status');document.body.append(flight);}}
 act(e,quiet=false){const r=journeyTransition(this.getState(),e);if(!r.ok){if(!quiet){this.toast(r.message);this.sound.effect('error');const el=$('#journey-message');if(el)el.textContent=r.message;}return false;}this.world.journeyRuntime.sync(r.state);this.setState(r.state,e.type==='flight-tick');if(!quiet){this.sound.effect(r.effect);this.toast(r.message);}return true;}
 modal(type,kicker,title,html){this.camera(false);this.showModal(type,kicker,title,html+'<p id="journey-message" role="status"></p>');}
 input(type,title,copy,event){this.modal('journey-password','301 — 400 / A MEMORY TO UNLOCK',title,copy+`<form id="journey-code-form"><label class="journey-input-label" for="journey-code">다섯 글자</label><input id="journey-code" class="journey-code" maxlength="5" autocomplete="off" autocapitalize="none" spellcheck="false" pattern="[A-Za-z]{5}" required aria-label="다섯 글자 비밀번호"><button class="primary" type="submit">${type==='lock'?'자물쇠 열기':'로그인'}</button></form>`);$('#journey-code-form').onsubmit=e=>{e.preventDefault();if(this.act({type:event,code:$('#journey-code').value})){this.closeModal();if(event==='computer')this.computer();else this.subtitle('“하영아! 또 구해 줬네. 이제 내가 꼭 따라갈게.”',6500);}};$('#journey-code').focus();}
 interact(id){const s=this.getState(),rt=this.world.journeyRuntime;if(rt.transition||s.seat&&!s.arrived&&s.zone==='plane')return;
  if(id==='journey-phone')return this.chat();
  if(id==='journey-lock')return this.input('lock','철창 안의 현수',`<div class="journey-dialogue">“자기야, 책상에 내 휴대폰 좀 봐 줘.<br>우리 어디로 가기로 했었지?”</div><div class="journey-lock-symbol">▢ ▢ ▢ ▢ ▢</div>`,'unlock');
  if(id==='journey-photo'){if(this.act({type:'photo'}))this.modal('journey-photo','THE PLACE WE ATE TOGETHER','이 식당, 기억나?',`<img class="journey-photo" src="${path}meaty.webp" alt="두 사람이 함께 먹었던 스테이크 사진"><div class="journey-blanks" aria-label="다섯 글자 빈칸">_ _ _ _ _</div><p class="body-copy">식당 이름을 기억해 줘.<br>책상에 놓인 컴퓨터도 같은 기억으로 잠겨 있어.</p>`);return;}
  if(id==='journey-computer')return this.computer();
  if(id==='journey-passport')return this.passport();
  if(id==='journey-up'||id==='journey-down'){if(this.act({type:id==='journey-up'?'church':'hell'}))this.closeModal();return;}
  if(id.startsWith('journey-pew-')){const seat=id.slice(12);if(seat!=='6B'){this.toast(`${seat} 좌석 아래에는 아무것도 없어.`);return;}this.modal('journey-bowl','2F · THE CHAPEL / SEAT 6B','좌석 아래 따뜻한 한 그릇',`<div class="journey-bowl-art">🥣</div><p class="body-copy">육회와 채소, 노른자가 올라간 육회비빔밥.<br>누군가 배고픈 채 기다리고 있는 것 같아.</p><button id="journey-take-bowl" class="primary" ${s.bowl||s.served?'disabled':''}>${s.bowl||s.served?'이미 챙긴 한 그릇':'육회비빔밥 챙기기'}</button>`);$('#journey-take-bowl').onclick=()=>{if(this.act({type:'bowl',seat}))this.closeModal();};return;}
  if(id==='journey-attendant')return this.attendant();
  if(id==='journey-board'){if(!s.served)this.attendant();else this.toast('탑승문이 열렸어요. 문 안으로 직접 걸어 들어가 주세요.');return;}
  if(id.startsWith('journey-seat-')){const seat=id.slice(13);this.modal('journey-seat','FIRST CLASS · JUST THE TWO OF US',seat+'에 앉을까?',`<p class="body-copy">기내에는 우리 둘뿐이야.<br>현수는 네 옆자리에 앉을 거야.</p><button id="journey-sit" class="primary">여기에 앉아서 출발하기</button>`);$('#journey-sit').onclick=()=>{if(this.act({type:'sit',seat})){this.closeModal();this.world.active=false;this.subtitle('안전벨트를 매 주세요. 인천에서 연태로 출발합니다.',5000);}};return;}
  if(id==='journey-land'){if(this.act({type:'disembark'})){this.closeModal();this.subtitle('“와… 빨간 계단이다. 같이 내려가자, 자기야.”',6000);}return;}
  if(id==='journey-dine'){if(this.act({type:'dine'}))this.conveyor();return;}
  if(id.startsWith('journey-food-')){if(this.act({type:'pick',id:id.slice(13)})&&this.getState().satisfied)this.gift();return;}
  if(id==='journey-hyunsu')return s.satisfied?this.gift():this.conveyor();
  if(id==='journey-exit'){if(this.act({type:'exit'}))this.modal('journey-finish','301 — 400 · OUR CHINA MEMORY','이제, 오백 번째 기억으로',`<div class="journey-finish-number">500</div><p class="body-copy">용암 속에서도, 구름 위에서도,<br>낯선 여행지에서도 늘 함께였어.<br><br>현수가 손을 내민다.<br>“다음 기억도 같이 가자, 하영아.”</p><p class="notice">301~400일 완료 · 500일로 향하는 문이 열렸습니다.</p><button id="journey-enter-bakery" class="primary">첫 번째 세계, 성심당으로</button><button id="journey-finish-rest" class="secondary">열린 문 앞에서 함께 쉬기</button>`);if($('#journey-enter-bakery'))$('#journey-enter-bakery').onclick=()=>this.onNext?.();if($('#journey-finish-rest'))$('#journey-finish-rest').onclick=()=>this.closeModal();}
 }
 chat(){this.act({type:'chat'});this.modal('journey-chat','HYUNSU’S PHONE','5월 16일의 대화',`<div class="memory-phone"><header><span>‹</span><b>하영 ♡</b><span>☰</span></header><div class="chat-date">2026년 5월 16일</div><div class="chat-author">현수</div><div class="chat-balloon incoming">자기야 우리 5.16에 어디가고 싶어?</div><div class="chat-author right">하영</div><div class="chat-balloon outgoing">222.44.444.66.1</div><div class="phone-keypad">${[['1','A ★'],['2','ABC'],['3','DEF'],['4','GHI'],['5','JKL'],['6','MNO'],['7','PQRS'],['8','TUV'],['9','WXYZ'],['*',''],['0','+'],['#','']].map(([n,l])=>`<div><b>${n}</b><small>${l}</small></div>`).join('')}</div><footer>같은 숫자를 누른 횟수로 글자 선택<br>★ 우리만의 단축키: 1 = A</footer></div>`);}
 computer(){if(!this.getState().computer)return this.input('computer','잠긴 컴퓨터',`<div class="journey-computer-lock"><span>HYUNSU</span><p>그날 저녁을 먹었던 곳.</p></div>`,'computer');this.modal('journey-computer','HYUNSU’S DESKTOP','중국으로 가는 서류',`<div class="journey-document"><img src="${path}entry-receipt.png" alt="첨부해 준 현수의 중국 입국 신고 확인서와 QR"></div><p class="body-copy">하영이의 휴대폰 카메라로 컴퓨터 화면의 QR을 비춰 봐.</p><button id="journey-open-camera" class="primary">내 휴대폰 카메라 켜기</button>`);$('#journey-open-camera').onclick=()=>{this.closeModal();this.camera(true);this.world.active=true;};}
 camera(on=!this.world.journeyRuntime.cameraOn){const rt=this.world.journeyRuntime;rt.cameraOn=on;rt.scanProgress=0;$('#journey-camera').hidden=!on;if(on){this.world.toggleView(false);this.toast('게임 속 휴대폰 카메라야. QR을 가운데에 맞춰 줘.');}}
 passport(){this.modal('journey-passport','OUR FIRST CHINA TRIP','여권과 여행 기록',`<div class="journey-passport-prop"><div><span>REPUBLIC OF KOREA</span><b>여 권</b><strong>✧</strong><span>PASSPORT</span></div><section><small>TRAVEL MEMORY</small><h3>YIM HYUNSU</h3><p>INCHEON → YANTAI</p><p>2026. 05. 16</p><p>함께 떠나는 중국 여행</p></section></div><p class="notice">책상 위의 여행용 여권 소품과 기념 기록.</p>${this.getState().ticket?'<button id="journey-show-pass" class="primary">발급된 탑승권 보기</button>':''}`);if($('#journey-show-pass'))$('#journey-show-pass').onclick=()=>this.ticket();}
 ticket(){if(!this.getState().ticket)return;this.modal('journey-ticket','OUR CHINA MEMORY · BOARDING PASS','우리의 중국행 탑승권',ticketMarkup(this.getState()));$('#journey-ticket-continue').onclick=()=>{this.closeModal();this.world.active=true;};}
 attendant(){const s=this.getState();this.modal('journey-attendant','CABIN CREW · GATE 2F',s.served?'탑승문을 열어 드렸어요':'잠시만요, 아직 탑승 대기 중이에요',`<div class="crew-identity"><span class="crew-wing" aria-hidden="true">✦</span><div><b>퍼스트 클래스 승무원</b><small>OUR MEMORY AIRLINES · GATE 2F</small></div><span class="crew-state ${s.served?'ready':''}">${s.served?'탑승 안내 중':'탑승 대기'}</span></div><div class="journey-dialogue">${s.served?'“덕분에 기분이 좋아졌어요.<br>제 옆에 열린 탑승문으로 걸어오세요.<br>기내에서는 마음에 드는 자리에 앉으시면 돼요!”':'“배도 고프고, 기분도 안 좋아요.<br>육회비빔밥 한 그릇만 있으면 좋을 텐데…”'}</div><button id="journey-serve" class="primary">${s.served?'열린 탑승문으로 가기':'육회비빔밥 건네기'}</button>${!s.served&&!s.bowl?'<p class="crew-clue">탑승권의 좌석 번호를 다시 살펴보세요.</p><button id="journey-crew-ticket" class="secondary">탑승권 다시 보기</button>':''}`);$('#journey-serve').onclick=()=>{if(s.served){this.closeModal();this.subtitle('FIRST CLASS 안내판 아래 문이 열렸어. 안으로 걸어 들어가자.',6000);}else if(this.act({type:'serve'}))this.attendant();};if($('#journey-crew-ticket'))$('#journey-crew-ticket').onclick=()=>this.ticket();}
 conveyor(){const s=this.getState();if(!s.dining)return;if(s.satisfied)return this.gift();this.modal('journey-conveyor','龍歌自助小火锅 · YANTAI WANDA','자기야, 내 입맛 알지?',`<div class="journey-dialogue">“좋아하는 메뉴 다섯 개로 골라 줘.<br>한 번 집은 건 또 가져오면 안 돼!”</div><div class="conveyor-window"><div class="conveyor-moving">${menu.filter(f=>![...s.chosen,...s.rejected].includes(f.id)).map(f=>`<button class="food-tray" data-food="${f.id}"><span class="food-illustration food-${f.id}" aria-hidden="true">${({beef:'🥩',brisket:'🥩',watermelon:'🍉',tofu:'◻',noodles:'🍜',mushroom:'🍄',bokchoy:'🥬',cilantro:'🌿',chicken:'🍗',quail:'🥚'})[f.id]}</span><b>${f.name}</b><small>집기</small></button>`).join('')}</div></div><p class="notice">좌우로 움직이는 레일 · 마우스를 올리거나 키보드로 선택하면 잠시 멈춰요.</p><div class="journey-food-progress"><strong>우리의 식탁 ${s.chosen.length} / 5</strong><div>${s.chosen.map(id=>`<span>${menu.find(f=>f.id===id).name}</span>`).join('')||'현수가 좋아하는 것만 담아 줘.'}</div></div>${s.rejected.length?`<p class="rejected-food">현수가 따로 놓은 접시: ${s.rejected.map(id=>menu.find(f=>f.id===id).name).join(', ')}<br>싫어하는 음식은 식탁에 올리지 않았어.</p>`:''}<button id="journey-leave-belt" class="secondary">직접 돌아다니며 레일에서 집기</button>`);$$('[data-food]').forEach(b=>b.onclick=()=>{if(this.act({type:'pick',id:b.dataset.food})){if(this.getState().satisfied)this.gift();else this.conveyor();}});$('#journey-leave-belt').onclick=()=>this.closeModal();}
 gift(){
  const s=this.getState();if(!s.satisfied)return;
  const beat=journeyStory(s),lines=text=>text.replaceAll('\n','<br>');
  const art=beat.art==='meal'?`<div class="journey-meal-art" aria-hidden="true"><div class="meal-steam"><i></i><i></i><i></i></div><div class="meal-pot">♨</div></div><div class="journey-story-dishes">${s.chosen.map(id=>`<span>${menu.find(f=>f.id===id).name}</span>`).join('')}</div>`:`<div class="zagee-cup ${s.cupInspected?'open':''}" aria-hidden="true"><div class="cup-straw"></div><div class="cup-lid"></div><div class="cup-body" style="background-image:url('${path}zagee-wrap.webp')"></div>${s.cupInspected?'<span class="cup-key">⚿</span>':''}</div>`;
  this.modal('journey-tea',`용가훠궈 · ${beat.chapter}`,beat.title,`<section class="journey-story" data-story-beat="${beat.id}">${art}<p class="journey-story-narration">${lines(beat.narration)}</p><div class="journey-dialogue">${lines(beat.quote)}</div><div class="journey-story-actions"><button id="journey-tea-action" class="primary">${beat.button}</button>${s.key?'':'<button id="journey-story-rest" class="secondary">잠시 식당 둘러보기</button>'}</div><p class="journey-story-note">${s.key?'문 앞에 서기 전까지, 조금 더 머물러도 좋아.':'서두르지 않아도 돼. 현수에게 다시 말을 걸면 이야기를 이어갈 수 있어.'}</p></section>`);
  $('#journey-tea-action').onclick=()=>{if(!beat.event)this.closeModal();else if(this.act({type:beat.event},true)){if(beat.event==='key')this.sound.effect('hatch');this.gift();}};
  if($('#journey-story-rest'))$('#journey-story-rest').onclick=()=>this.closeModal();
 }
 tick(dt,paused){const rt=this.world.journeyRuntime,s=this.getState();$('#journey-camera').hidden=!rt.cameraOn||paused;$('#journey-flight').hidden=!(s.zone==='plane'&&s.seat&&!s.arrived)||paused;if(paused)return;
  if(rt.cameraOn){const aligned=rt.scanAligned();rt.scanProgress=aligned?Math.min(1.3,rt.scanProgress+dt):0;$('#scan-copy').textContent=aligned?'QR을 인식하고 있어… 그대로 맞춰 줘.':'컴퓨터의 QR을 중앙 네모 안에 맞춰 줘.';$('#scan-meter-fill').style.width=rt.scanProgress/1.3*100+'%';if(rt.scanProgress>=1.3&&this.act({type:'scan',aligned:true})){this.camera(false);this.ticket();}}
  if(s.zone==='plane'&&s.seat&&!s.arrived){this.act({type:'flight-tick',dt},true);const next=this.getState();$('#journey-flight').innerHTML=`<span>ICN <b>✈</b> YNT</span><strong>${next.flight<3?'이륙합니다':next.flight<8?'구름 위를 지나고 있어요':'연태에 접근 중입니다'}</strong><small>${Math.max(0,Math.ceil(10-next.flight))}초 후 도착 · Esc 일시정지</small>`;if(next.arrived){$('#journey-flight').hidden=true;this.subtitle('연태에 도착했습니다. 즐거운 여행 되세요!',7500);this.toast('도착했어! 앞쪽 출구로 걸어가 내려 줘.');this.sound.effect('success');}}
 }
 hint(){const s=this.getState();const hint=!s.freed?'같은 숫자를 반복한 횟수로 알파벳을 찾아 봐. 222=C, 44=H, 444=I, 66=N. 이 휴대폰에서 1은 A야.':!s.computer?'사진은 meaty에서 먹었던 스테이크야. 식당 이름 다섯 글자를 컴퓨터에 입력해 봐.':!s.ticket?'C로 하영이의 카메라를 켜고, 컴퓨터 QR을 가운데에 1초 정도 맞춰 줘.':!s.bowl&&!s.served?'GATE 2F는 2층. 작은 계단을 올라가 교회의 6B 좌석을 살펴봐.':!s.served?'육회비빔밥을 승무원에게 건네 줘.':!s.arrived?'비행기에 타서 어느 자리든 앉으면 10초 동안 비행해.':!s.satisfied?'현수는 소고기, 수박, 당면, 청경채, 치킨을 좋아해. 양지와 소고기는 서로 다른 접시야.':!s.tea?'현수에게 말을 걸어 같이 식사하고 여행 이야기를 나눠 봐.':!s.key?'인벤토리의 ZAGEE를 열면 컵을 살펴보던 장면을 이어갈 수 있어.':'금빛 500이 적힌 문에 열쇠를 사용해 줘.';this.modal('journey-hint','OUR CHINA MEMORY · HINT','현수에게 물어보기',`<p class="body-copy">${journeyObjective(s)}</p><details><summary>한 단계 더 힌트 보기</summary><p class="body-copy">${hint}</p></details>`);}
}
