import {junctionTransition,junctionObjective,redLines,ipadLetter} from './junction-state.js';
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)],esc=t=>String(t).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
export class JunctionController{
 constructor(api){Object.assign(this,api);this.routeValue='';this.lastCaption='';if(!$('#junction-caption')){const e=document.createElement('div');e.id='junction-caption';e.hidden=true;e.setAttribute('aria-live','polite');document.body.append(e);}}
 act(e){const before=this.getState(),r=junctionTransition(before,e);if(!r.ok){if(r.message){this.toast(r.message);this.sound.effect('error');if($('#junction-error'))$('#junction-error').textContent=r.message;}return false;}
  const silent=['tick','draft'].includes(e.type);this.setState(r.state,silent);this.world.junctionRuntime.state=r.state;
  if(!silent||before.phase!==r.state.phase||before.yellowSolved!==r.state.yellowSolved)this.world.junctionRuntime.sync(r.state);
  if(!silent){if(r.effect)this.sound.effect(r.effect);if(r.message)this.toast(r.message);}return true;
 }
 modal(title,body){this.showModal('junction','401 — 500 · POSTECH / JUNCTION KOREA 2026',title,body+'<p id="junction-error" class="puzzle-error" role="status" aria-live="polite"></p>');}
 interact(id){
  if(this.getState().completed)return this.finish();
  if(id==='junction-red')return this.red();if(id==='junction-red-button'||id==='junction-green-button'){this.act({type:'red-button',color:id==='junction-red-button'?'red':'green'});return;}
  if(id==='junction-blue')return this.blue();if(id==='junction-yellow')return this.yellow();if(id==='junction-bin')return this.bin();if(id==='junction-coat')return this.coat();if(id==='junction-hyunsu')return this.hyunsu();if(id==='junction-ipad')return this.tablet();if(id==='junction-envelope')return this.writeLetter();
  if(id.startsWith('junction-minion-'))return this.act({type:'minion',id:Number(id.at(-1))});
  if(['junction-victory','junction-top'].includes(id))return this.act({type:'take-drink',id:id.slice(9)});
 }
 red(){const s=this.getState();if(!s.usbInserted){this.modal('꺼진 빨강 모니터','<p class="body-copy">성심당에서 가져온 USB에 무언가 담겨 있어.<br>모니터 앞 연결 단자에 꽂아 보자.</p><button id="junction-insert-usb" class="primary">USB 연결하기</button>');$('#junction-insert-usb').onclick=()=>{if(this.act({type:'insert-usb'}))this.red();};return;}
  if(!s.redPowered)return this.route();if(s.redSolved){this.modal('빨강 빛의 기억','<div class="junction-status red">RED · COMPLETE</div><p class="body-copy">빨강 광선은 계속 하늘을 향하고 있어.<br>이제 파랑 모니터를 살펴보자.</p>');return;}
  this.modal('빨강 모니터',`<div class="junction-monitor red"><small>구절 ${Math.floor(s.redPresses/2)+1} / 4</small><p id="junction-red-line">${redLines[Math.floor(s.redPresses/2)]}</p><span>${s.redPresses%2} / 2</span></div><div class="junction-buttons"><button data-color="red" class="junction-red-button">빨강</button><button data-color="green" class="junction-green-button">초록</button></div>`);
  $$('[data-color]').forEach(b=>b.onclick=()=>{this.act({type:'red-button',color:b.dataset.color});this.red();});
 }
 route(){this.modal('START에서 여기까지',`<p class="body-copy">무대 쪽이 위쪽(↑)이야.<br><strong>START → 미로 속 빨강 방의 바닥 표식</strong>까지 가장 짧은 길을 떠올려 봐.<br>방향이 바뀔 때마다 하나씩. 같은 방향으로 이어 걸으면 한 번만.</p><output id="junction-route-output" class="junction-route"></output><div class="junction-directions">${[['U','↑'],['L','←'],['D','↓'],['R','→']].map(([d,a])=>`<button data-dir="${d}" aria-label="${a}">${a}</button>`).join('')}</div><div class="junction-actions"><button id="junction-route-reset" class="secondary">지우기</button><button id="junction-route-submit" class="primary">전원 켜기</button></div>`);
  const draw=()=>$('#junction-route-output').textContent=[...this.routeValue].map(k=>({U:'↑',D:'↓',L:'←',R:'→'}[k])).join(' ')||'방향키를 입력해 줘';draw();const append=d=>{this.routeValue=(this.routeValue+d).slice(0,32);draw();};$$('[data-dir]').forEach(b=>b.onclick=()=>append(b.dataset.dir));$('#junction-route-reset').onclick=()=>{this.routeValue='';draw();};$('#junction-route-submit').onclick=()=>{if(this.act({type:'route',value:this.routeValue}))this.red();};
  if(this.arrowHandler)document.removeEventListener('keydown',this.arrowHandler);this.arrowHandler=e=>{if($('#modal-backdrop').hidden||!$('#junction-route-output'))return;const d={ArrowUp:'U',ArrowDown:'D',ArrowLeft:'L',ArrowRight:'R'}[e.code];if(d){e.preventDefault();append(d);}};document.addEventListener('keydown',this.arrowHandler);
 }
 input(title,body,type){this.modal(title,body+'<form id="junction-answer-form"><label for="junction-answer">빈칸의 답</label><input id="junction-answer" autocomplete="off" spellcheck="false" maxlength="40" required><button class="primary" type="submit">확인</button></form>');$('#junction-answer-form').onsubmit=e=>{e.preventDefault();if(this.act({type,value:$('#junction-answer').value})){if(type==='seconds')this.coat();else this.yellow();}};}
 blue(){const s=this.getState();if(!s.redSolved){this.toast('먼저 빨강 모니터를 해결해 줘.');return;}if(s.coatSpawned)return this.coat();if(!s.bluePowered){this.modal('BLUE를 떠올려 봐',`<div class="junction-monitor blue"><p>BIGBANG · BLUE</p><small>남겨 둘 것과 버릴 것</small></div><p class="body-copy">VICTORY 탄산수와 T.O.P 커피를 들고,<br>옆의 쓰레기통으로 가 보자.</p><p class="junction-small">쓰레기통에 넣은 물건 · ${s.trashed.length} / 2</p>`);return;}
  this.input('그 사이, 짧은 시간',`<div class="junction-monitor blue"><p>붉은색, 푸른색, 그 사이 (__)</p><p>그 짧은 시간~</p><p>노란색 빛을 내는 저기 저 신호등</p></div><p class="junction-small">숫자와 영어 seconds를 붙여서 입력해 줘.</p>`,'seconds');
 }
 bin(){const s=this.getState();this.modal('쓰레기통',`<p class="body-copy">들고 온 물건을 쓰레기통에 넣자.</p><div class="junction-actions">${['victory','top'].map(id=>`<button data-trash="${id}" class="secondary" ${!s.drinks.includes(id)||s.trashed.includes(id)?'disabled':''}>${id==='victory'?'VICTORY 탄산수':'T.O.P 커피'} ${s.trashed.includes(id)?'· 버림':'버리기'}</button>`).join('')}</div>`);$$('[data-trash]').forEach(b=>b.onclick=()=>{if(this.act({type:'trash',id:b.dataset.trash})){if(this.getState().bluePowered)this.closeModal();else this.bin();}});}
 coat(){const s=this.getState();if(!s.coatSpawned)return;this.modal('모니터 아래에서 나온 옷',`<div class="junction-shirt" aria-label="옷의 뒷면"><span>+5</span></div><p class="junction-small">뒷면에 빨간색으로 새겨진 +5</p>${s.coatTaken?'<p class="body-copy">옷을 들고 있어. 가운데 신호등으로 가 보자.</p>':'<button id="junction-take-coat" class="primary">옷 들기</button>'}`);if($('#junction-take-coat'))$('#junction-take-coat').onclick=()=>{if(this.act({type:'take-coat'}))this.closeModal();};}
 yellow(){const s=this.getState();if(!s.blueSolved)return this.toast('빨강, 파랑, 노랑 순서야. 먼저 옷을 들어 줘.');if(!s.offered){this.modal('세 친구를 위한 자리',`<div class="junction-dolls">${[0,1,2].map(i=>`<span class="${s.minions.includes(i)?'found':''}">●</span>`).join('')}</div><p class="body-copy">미로 곳곳에 숨어 있는 미니언 인형 세 개.<br>모두 모아 신호등 아래 제단에 놓아 줘.</p><button id="junction-offer" class="primary">인형 ${s.minions.length} / 3개 바치기</button>`);$('#junction-offer').onclick=()=>{if(this.act({type:'offer'}))this.yellow();};return;}
  if(!s.brandSolved){this.input('이 옷의 이름은?',`<div class="junction-shirt"><span>+5</span></div><p class="body-copy">파랑 화면의 짧은 시간에,<br>옷 뒤의 빨간 숫자를 더해 봐.<br>이 옷의 브랜드는 무엇일까?</p>`,'brand');return;}
  this.modal('그때의 옷',`<p class="junction-memory">너는 항상 이 옷을 싫어했어.<br>난 좋아했는데....</p><p class="body-copy">나도 이런 안좋은 기억 가지고 싶지 않아.</p><button id="junction-go-hyunsu" class="primary">현수에게 다가가기</button>`);$('#junction-go-hyunsu').onclick=()=>this.closeModal();
 }
 hyunsu(){const s=this.getState();if(s.phase==='letter')return this.writeLetter();if(s.phase==='tablet')return this.toast('세 광선이 남긴 아이패드에 글이 있어.');if(!s.brandSolved)return this.toast('현수가 신호등의 마지막 빛을 기다리고 있어.');if(s.complimented)return this.toast('현수의 손을 꼭 잡아 줘.');this.modal('현수에게',`<p class="body-copy">${s.dressed?'그 옷을 입은 현수가 머뭇거린다.<br>진심으로 잘 어울린다고 말해 주자.':'이 옷을 좋아했던 현수에게 직접 입혀 주자.'}</p><button id="junction-hyunsu-action" class="primary">${s.dressed?'“잘 어울려, 현수야. 정말 멋있어!”':'현수에게 옷 입히기'}</button>`);$('#junction-hyunsu-action').onclick=()=>{if(this.act({type:s.dressed?'compliment':'dress'})){if(s.dressed)this.closeModal();else this.hyunsu();}};}
 tablet(){const s=this.getState();if(s.phase==='letter')return this.writeLetter();if(!this.act({type:'read-tablet'}))return;this.modal('아이패드에 남은 편지',`<article class="junction-ipad"><small>현수 → 하영 · 500일</small><p>${esc(ipadLetter)}</p></article><button id="junction-open-envelope" class="primary">편지봉투 열기</button>`);$('#junction-open-envelope').onclick=()=>{if(this.act({type:'envelope'}))this.writeLetter();};}
 writeLetter(){const s=this.getState();if(!s.tabletRead)return;if(s.phase==='tablet')this.act({type:'envelope'});this.modal('현수에게 쓰는 500일 편지','<div class="junction-envelope-paper"><label for="junction-letter">하고 싶은 말을 자유롭게 적어 줘.</label><textarea id="junction-letter" rows="9" maxlength="12000" placeholder="현수에게…"></textarea><small>작성 중인 편지는 이 브라우저에 자동으로 간직해요.</small></div><button id="junction-send-letter" class="primary">현수에게 편지 보내기</button>');$('#junction-letter').value=s.draft;$('#junction-letter').oninput=e=>this.act({type:'draft',value:e.target.value});$('#junction-send-letter').onclick=()=>{this.act({type:'draft',value:$('#junction-letter').value});if(this.act({type:'send-letter'}))this.closeModal();};}
 tick(dt){let s=this.getState();if(['collapse','recovery','walk','hearts'].includes(s.phase)&&dt>0){const old=s.phase;this.act({type:'tick',dt});s=this.getState();if(old!==s.phase){if(s.phase==='tablet'){this.world.active=true;this.subtitle('세 빛이 모인 곳에 아이패드가 나타났다.',6500);}if(s.phase==='complete')this.finish();}}
  const t=s.phaseTime,caption=s.phase==='collapse'?(t<2?'뭐야, 요기가 ㅇ어디지?':t<4?'요기는 어디지? 내가 왜 이렇게 된거지?':'현수가 머리를 감싸 쥐고 쓰러졌다…'):s.phase==='recovery'?(t<3?'으… 머리가… 더 아파…':t<5?'하영이의 편지… 우리의 500일…':'기억이 돌아왔어! 하영이는 날 사랑해!!!'):s.phase==='walk'?'현수가 하영이의 손을 잡고, 중앙의 원으로 이끈다.':s.phase==='hearts'?(t<4?'우리의 500일에, 하늘이 하트를 선물한다.':'사랑해 하영아!'):'';
  if(caption!==this.lastCaption){$('#junction-caption').textContent=caption;$('#junction-caption').hidden=!caption;this.lastCaption=caption;}
 }
 finish(){this.modal('500일 방탈출을 완료하였습니다',`<div class="junction-finale-heart">♥</div><p class="junction-memory">기억이 돌아왔어!<br>하영이는 날 사랑해!!!</p><p class="body-copy">사랑해 하영아!<br>마지막으로, 너에게 보여 주고 싶은 우리의 이야기가 있어.</p><button id="junction-prologue" class="primary">프롤로그 보기</button>`);$('#junction-prologue').onclick=()=>location.assign(`${location.pathname}?preview=prologue`);}
 hint(){this.modal('함께 되찾는 기억',`<p class="body-copy">${junctionObjective(this.getState())}</p><details><summary>단서 더 보기</summary><p class="body-copy">미로는 무대 쪽을 ↑로 읽어. 빨강은 구절마다 두 번씩 눌러. 파랑에는 버릴 물건 두 개와 짧은 시간이 있어. 그 시간에 옷의 +5를 더하면 다음 답이 돼.</p></details>`);}
}
