import {ingredients,recipes,recipeKeys,lineSeven} from './kitchen-data.js';
import {kitchenTransition} from './kitchen-state.js';
import {categoryNames,modelIcons,foodReferences} from './market-catalog.js';
import {FoodPreview} from './kitchen-world.js';
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
const heatNames={off:'불 끄기',low:'약불',medium:'중불'};
export class KitchenController{
 constructor(api){Object.assign(this,api);this.preview=null;this.kind=null;this.sequence=[];this.heat='off';this.lastSecond=-1;}
 closeView(){this.preview?.dispose();this.preview=null;this.kind=null;}
 act(event){const result=kitchenTransition(this.getState(),event);if(!result.ok){this.sound.effect('error');const el=$('#cook-message');if(el)el.textContent=result.message;this.toast(result.message);return false;}
  this.setState(result.state);this.world.kitchenRuntime.sync(result.state);this.toast(result.message);
  this.sound.effect(result.effect==='power'?'power':result.effect==='order'?'order':result.effect==='cook'?(event.action==='dry'?'wash':event.action==='egg-rice'?'chop':'sizzle'):result.effect==='complete-dish'?'success':result.effect||'paper');return true;
 }
 interact(id){
  if(id==='kitchen-power'){this.openPower();return;}
  if(!this.getState().lights){this.toast('빛나는 7호선 노선도부터 살펴봐.');return;}
  if(id.startsWith('kitchen-market'))this.openMarket(id==='kitchen-market'?'all':id.slice('kitchen-market-'.length));
  else if(id.startsWith('cook-'))this.openRecipe(id.slice(5));
  else if(id==='kitchen-courier'){if(this.act({type:'cook',recipe:'chicken',action:'receive',heat:'off'})){this.sound.effect('doorbell');this.openRecipe('chicken');}}
  else if(id==='kitchen-exit'){
   if(!this.getState().completed){this.toast('네 방향 요리를 모두 완성하면 다음 문이 열려.');return;}
   this.showModal('cooking-complete','200 DAYS · MADE WITH LOVE','우리의 두 번째 식탁이 완성됐어',`<p class="body-copy">마음을 담아 요리하던 날들을 모두 찾았네.<br>이제 201~300일의 기억으로 가자. 이번에는 현수에게 하영이의 도움이 필요해.</p><button id="kitchen-finish" class="primary">201~300일 · 현수를 구해라 →</button>`);$('#kitchen-finish').onclick=this.onExit;
  }
 }
 openPower(){
  const state=this.getState();this.sequence=[];
  this.showModal('subway','LINE 07 · THE FIRST LIGHT','현수가 머물렀던 시간',`<p class="body-copy">모두 7호선에 있던 수학학원.<br>현수가 <strong>짧게 일한 곳부터 오래 일한 곳까지</strong> 역을 눌러 줘.</p><div class="station-sequence" id="station-sequence"><span>?</span><b>&lt;</b><span>?</span><b>&lt;</b><span>?</span></div><div class="subway-map">${lineSeven.map(n=>`<button class="station" data-station="${n}" ${state.lights?'disabled':''}><i></i>${n}</button>`).join('')}</div><p id="cook-message" role="status">${state.lights?'이 기억은 이미 불을 밝혀 줬어.':'상동에서 신대방삼거리까지의 7호선 구간'}</p><div class="modal-actions"><button id="subway-reset" class="secondary">다시 고르기</button><button id="subway-check" class="primary" ${state.lights?'disabled':''}>전원 켜기</button></div>`);this.kind='subway';
  const draw=()=>{$('#station-sequence').innerHTML=Array.from({length:3},(_,i)=>`${i?'<b>&lt;</b>':''}<span>${this.sequence[i]||'?'}</span>`);$$('[data-station]').forEach(b=>b.classList.toggle('selected',this.sequence.includes(b.dataset.station)));};
  $$('[data-station]').forEach(b=>b.onclick=()=>{if(this.sequence.length===3)this.sequence=[];if(!this.sequence.includes(b.dataset.station))this.sequence.push(b.dataset.station);this.sound.effect('dial');draw();});
  $('#subway-reset').onclick=()=>{this.sequence=[];draw();};$('#subway-check').onclick=()=>{if(this.act({type:'power',stations:this.sequence})){this.closeModal();this.world.active=true;}};
 }
 openMarket(category='all'){
  const bag=this.getState().bag,all=Object.entries(ingredients),count=all.length;
  this.showModal('market','200 MARKET · OPEN FOR OUR MEMORIES','우리 둘의 작은 편의점',`<div class="market-heading"><p class="body-copy">${count}가지 재료와 간식이 진열되어 있어.<br>레시피를 떠올리며 필요한 재료를 담아 줘.</p><label class="market-search">재료 찾기<input id="market-search" type="search" placeholder="새우, 우유, 초콜릿…" autocomplete="off"></label></div><div class="market-tabs">${Object.entries(categoryNames).map(([id,t])=>`<button class="${id===category?'active':''}" data-category="${id}">${t}</button>`).join('')}</div><div class="market-grid">${all.filter(([,v])=>category==='all'||v[2]===category).map(([id,[name,amount,cat]])=>`<article class="ingredient ${cat}" data-product="${id}" data-name="${name}">${modelIcons[id]?`<img src="/assets/market-icons/${modelIcons[id]}.png" alt="${name} 3D 모형" loading="lazy">`:`<span class="ingredient-shape ${cat}" aria-hidden="true"></span>`}<b>${name}</b><small>${amount}</small><span class="bag-amount">가방 ${bag[id]||0}</span><div class="market-card-actions"><button data-return="${id}" aria-label="${name} 하나 돌려놓기" ${bag[id]?'':'disabled'}>−</button><button data-ingredient="${id}" aria-label="${name} 하나 담기">담기 ＋</button></div></article>`).join('')}</div><p id="market-empty" hidden>이 코너에서는 찾지 못했어. 전체 코너도 살펴봐.</p><p id="cook-message" role="status">필요 없는 재료는 − 버튼으로 돌려놓을 수 있어.</p><small class="market-credit">음식 3D 모형 · <a href="https://kenney.nl/assets/food-kit" target="_blank" rel="noopener">Kenney Food Kit (CC0)</a> · 과일 코너의 사과 · <a href="https://polyhaven.com/a/food_apple_01" target="_blank" rel="noopener">Oliver Harries / Poly Haven (CC0)</a></small>`);this.kind='market';
  $$('[data-category]').forEach(b=>b.onclick=()=>this.openMarket(b.dataset.category));
  const refresh=id=>{const card=$(`[data-product="${id}"]`),n=this.getState().bag[id]||0;card.querySelector('.bag-amount').textContent='가방 '+n;card.querySelector('[data-return]').disabled=!n;};
  $$('[data-ingredient]').forEach(b=>b.onclick=()=>{if(this.act({type:'take',item:b.dataset.ingredient}))refresh(b.dataset.ingredient);});
  $$('[data-return]').forEach(b=>b.onclick=()=>{if(this.act({type:'return',item:b.dataset.return}))refresh(b.dataset.return);});
  $('#market-search').oninput=e=>{const q=e.target.value.trim().replace(/\s/g,'');let shown=0;$$('[data-product]').forEach(card=>{card.hidden=!card.dataset.name.replace(/\s/g,'').includes(q);if(!card.hidden)shown++;});$('#market-empty').hidden=shown>0;};
 }
 openRecipe(key){
  const r=recipes[key],state=this.getState(),index=state.progress[key],step=r.steps[index],done=!step;this.heat=this.world.kitchenRuntime.effects[key]?.heat||'off';const ref=foodReferences[key];
  const preview=`<div class="food-view-tabs"><button data-food-view="model" class="active">지금 만드는 음식 · 3D</button><button data-food-view="photo">실제 음식 사진</button></div><div class="dish-preview" id="model-view"><canvas id="dish-preview" aria-label="${r.name}의 현재 조리 모습"></canvas><span>드래그해서 음식 돌려 보기 · 불꽃과 김을 살펴봐</span></div><figure class="food-reference" id="photo-view" hidden><img src="/assets/food-reference/${key}.jpg" alt="${ref.label} 참고 사진"><figcaption><b>${ref.label}</b><span>실제 음식 참고 사진 · 게임 속 조리 구성과 다를 수 있어요.</span><small><a href="${ref.source}" target="_blank" rel="noopener">${ref.author} / Wikimedia Commons</a> · <a href="${ref.licenseUrl}" target="_blank" rel="noopener">${ref.license}</a> · 축소본, 내용 변경 없음</small></figcaption></figure>`;
  const needs=step?.need.map(k=>`<span class="${state.bag[k]?'ready':'missing'}">${ingredients[k][0]} ${state.bag[k]?'✓':'· 마트에서 가져오기'}</span>`).join('')||'';
  let actions='';
  if(step?.id==='order')actions=`<div class="phone"><div class="phone-brand">배달의민족 <small>게임 속 주문</small></div><label>어떤 가게를 찾고 있어?<input id="delivery-search" placeholder="가게 이름 검색" autocomplete="off"></label><button id="delivery-find" class="secondary">검색</button><div id="bbq-menu" hidden><h3>BBQ</h3><p>황올반 + BBQ양념반</p><label>부위<select id="chicken-cut"><option value="whole">한 마리</option><option value="drumsticks">닭다리만</option><option value="wings">윙·봉</option></select></label><label>맛<select id="chicken-flavor"><option value="fried">후라이드</option><option value="half">양념 반 / 후라이드 반</option><option value="sauced">양념</option></select></label><button id="send-delivery" class="primary">이 메뉴로 주문하기</button></div><small>게임 안에서 배달되는 주문이에요.</small></div>`;
  else if(step?.id==='receive')actions=`<div class="delivery-tracker"><span id="delivery-clock"></span><p>배달기사가 원형 홀 입구에서 다가오고 있어.<br>조리대를 나가 기사 앞에서 E를 눌러 상자를 받아 줘.</p><button id="go-receive" class="primary">배달 받으러 나가기</button></div>`;
  else if(step)actions=`<div class="heat-control" role="group" aria-label="불 세기">${Object.entries(heatNames).map(([id,name])=>`<button data-heat="${id}" class="${this.heat===id?'active':''}">${name}</button>`).join('')}</div>${step.id==='measure'?`<div class="sauce-measures">${[['ketchup','케첩'],['chili','고춧가루'],['sugar','설탕'],['soy','간장'],['vinegar','식초']].map(([id,name])=>`<label>${name}<select data-measure="${id}" aria-label="${name} 큰술">${[0,1,2,3].map(n=>`<option value="${n}">${n} T</option>`).join('')}</select></label>`).join('')}</div>`:''}${step.id==='water'?'<label class="water-control">중탕 물 온도<select id="water-temperature"><option value="20">20°C</option><option value="50">50°C</option><option value="100">100°C</option></select></label>':''}<p class="step-guide">지금 할 작업을 레시피에서 찾아 눌러 줘.</p><div class="cooking-actions">${r.steps.filter(s=>!['order','receive'].includes(s.id)).map(s=>`<button data-action="${s.id}" class="secondary" ${r.steps.indexOf(s)<index?'disabled':''}>${r.steps.indexOf(s)<index?'✓ ':''}${s.title}</button>`).join('')}</div>`;
  this.showModal('cooking','200 DAYS · '+r.clock+' KITCHEN',r.name,`<div class="kitchen-layout"><section>${preview}<div class="cook-progress"><i style="width:${index/r.steps.length*100}%"></i></div><p class="dish-count">${done?'완성했어!':`${index} / ${r.steps.length} 단계`}</p><p id="cook-message" role="status">${done?'정성을 담은 한 끼가 식탁에 놓였어.':step.detail}</p><div class="needed-items">${needs}</div></section><section><p class="recipe-intro">${r.intro}</p><details class="recipe-book" open><summary>이 방의 레시피</summary><ol>${r.steps.map((s,i)=>`<li class="${i<index?'done':i===index?'current':''}"><b>${s.title}</b><small>${s.detail}</small></li>`).join('')}</ol><a href="${r.source}" target="_blank" rel="noopener">참고 레시피 · ${r.sourceName} ↗</a></details></section></div>${actions}${done?'<button id="leave-kitchen" class="primary">다른 요리방 둘러보기</button>':''}`);
  this.kind=key;this.preview=new FoodPreview($('#dish-preview'),this.world.kitchenRuntime,key,index);this.preview.setHeat(this.heat);
  $$('[data-food-view]').forEach(b=>b.onclick=()=>{const photo=b.dataset.foodView==='photo';$('#photo-view').hidden=!photo;$('#model-view').hidden=photo;$$('[data-food-view]').forEach(el=>el.classList.toggle('active',el===b));});
  if($('#delivery-find'))$('#delivery-find').onclick=()=>{const found=$('#delivery-search').value.trim().replace(/\s/g,'').toLowerCase();if(found==='bbq'||found==='비비큐'){$('#bbq-menu').hidden=false;}else $('#cook-message').textContent='BBQ 또는 비비큐를 검색해 줘.';};
  if($('#send-delivery'))$('#send-delivery').onclick=()=>{if(this.act({type:'order',recipe:key,brand:'BBQ',cut:$('#chicken-cut').value,flavor:$('#chicken-flavor').value}))this.openRecipe(key);};
  if($('#go-receive'))$('#go-receive').onclick=()=>this.closeModal();if($('#leave-kitchen'))$('#leave-kitchen').onclick=()=>this.closeModal();
  $$('[data-heat]').forEach(b=>b.onclick=()=>{this.heat=b.dataset.heat;this.world.kitchenRuntime.setHeat(key,this.heat);this.preview?.setHeat(this.heat);$$('[data-heat]').forEach(el=>el.classList.toggle('active',el===b));this.sound.effect('dial');});
  $$('[data-action]').forEach(b=>b.onclick=()=>{const event={type:'cook',recipe:key,action:b.dataset.action,heat:this.heat};if(step?.id==='measure')event.amounts=$$('[data-measure]').map(el=>+el.value);if(step?.id==='water')event.temperature=+$('#water-temperature').value;
   if(this.act(event)){if(key==='pepero'&&['water','melt'].includes(event.action))this.world.kitchenRuntime.effects.pepero.setSteam(.8);this.openRecipe(key);const canvas=$('#dish-preview');canvas?.classList.add('cooking-motion');}
  });this.tick();
 }
 tick(){if(Object.values(this.world.kitchenRuntime.effects).some(fx=>fx.heat!=='off')&&!this.sound.paused&&Date.now()>(this.sizzleAt||0)){this.sound.effect('sizzle');this.sizzleAt=Date.now()+950;}const s=this.getState();if(s.orderAt!==null&&!s.received){const seconds=Math.max(0,Math.ceil((s.orderAt+10000-Date.now())/1000));const clock=$('#delivery-clock');if(clock)clock.textContent=seconds?`배달 중 · ${seconds}초 뒤 도착`:'배달 완료 · 기사 앞에서 E';if(seconds===0&&this.lastSecond!==0){this.sound.effect('doorbell');this.toast('띵동! 입구 쪽에서 배달기사가 상자를 들고 기다려.');}this.lastSecond=seconds;}}
}
