export const extraIngredients={carrot:['당근','두 개','produce'],onion:['양파','두 개','produce'],leek:['대파','한 단','produce'],tomato:['토마토','세 개','produce'],broccoli:['브로콜리','한 송이','produce'],cabbage:['양배추','반 통','produce'],mushroom:['양송이','한 팩','produce'],paprika:['파프리카','두 개','produce'],corn:['옥수수','두 개','produce'],apple:['사과','세 개','produce'],pear:['배','두 개','produce'],banana:['바나나','한 송이','produce'],orange:['오렌지','세 개','produce'],lemon:['레몬','두 개','produce'],avocado:['아보카도','두 개','produce'],strawberry:['딸기','한 팩','produce'],milk:['우유','한 팩','dairy'],cheese:['치즈','한 조각','dairy'],honey:['꿀','한 병','pantry'],mustard:['머스터드','한 병','pantry'],salt:['소금','한 통','pantry'],peanutbutter:['땅콩버터','한 병','pantry'],bread:['식빵','한 봉지','bakery'],croissant:['크루아상','두 개','bakery'],cookies:['초코 쿠키','한 봉지','bakery'],water:['생수','한 병','drinks'],soda:['탄산음료','한 캔','drinks'],juice:['과일주스','한 팩','drinks'],fish:['생선 필레','한 팩','seafood'],bacon:['베이컨','한 팩','seafood'],sausage:['소시지','한 팩','seafood'],chocolatebar:['초콜릿 바','두 개','bakery']};
export const categoryNames={all:'전체',seafood:'냉장·해산물',produce:'과일·채소·밥',pantry:'소스·조미료',dairy:'유제품·디저트',bakery:'베이커리',drinks:'음료',pack:'포장 용품'};
export const modelIcons={carrot:'carrot',onion:'onion',leek:'leek',tomato:'tomato',broccoli:'broccoli',cabbage:'cabbage',mushroom:'mushroom',paprika:'paprika',corn:'corn',apple:'apple',pear:'pear',banana:'banana',orange:'orange',lemon:'lemon',avocado:'avocado',strawberry:'strawberry',milk:'carton',cheese:'cheese-cut',honey:'honey',mustard:'bottle-musterd',salt:'shaker-salt',peanutbutter:'peanut-butter',bread:'bread',croissant:'croissant',cookies:'cookie-chocolate',water:'soda-bottle',soda:'soda-can',juice:'carton-small',fish:'fish',bacon:'bacon-raw',sausage:'meat-sausage',chocolatebar:'candy-bar-wrapper',egg:'egg',oil:'bottle-oil',ketchup:'bottle-ketchup',soy:'soy',pepper:'shaker-pepper',chocolate:'chocolate',box:'styrofoam'};
export const foodReferences={
 chili:{label:'새우볶음밥의 밥·새우 질감',author:'Shene81',license:'CC BY 3.0',licenseUrl:'https://creativecommons.org/licenses/by/3.0/',source:'https://commons.wikimedia.org/wiki/File:Korean_Shrimp_Fried_Rice.jpg'},
 chicken:{label:'후라이드 닭다리의 형태와 튀김옷',author:'Mumujit',license:'CC BY-SA 4.0',licenseUrl:'https://creativecommons.org/licenses/by-sa/4.0/',source:'https://commons.wikimedia.org/wiki/File:Fried_chicken_drumsticks.jpg'},
 garlic:{label:'갈릭새우의 익은 속살과 윤기',author:'Banej',license:'CC BY-SA 4.0',licenseUrl:'https://creativecommons.org/licenses/by-sa/4.0/',source:'https://commons.wikimedia.org/wiki/File:Gambas_Al_Ajillo_(Spanish_Garlic_Shrimp).jpg'},
 pepero:{label:'초콜릿 코팅과 아몬드 토핑',author:'Evan-Amos',license:'CC0',licenseUrl:'https://creativecommons.org/publicdomain/zero/1.0/',source:'https://commons.wikimedia.org/wiki/File:Pepero-Almond-Sticks.jpg'}
};
