import {rescueTransition,rescueObjectives} from './rescue-state.js';
import {regionAt,regionLabel} from './rescue-map.js';
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
export class RescueController{
 constructor(api){Object.assign(this,api);this.color='blue';this.alarmAt=-100;this.wasPaused=false;this.audio=new Audio('/assets/rescue/earthquake-ja.mp3');this.audio.preload='auto';if(!$('#rescue-alert')){const el=document.createElement('aside');el.id='rescue-alert';el.setAttribute('role','status');el.hidden=true;el.innerHTML='<b>緊急地震速報 · M 6.2</b><span>규모 6.2의 강한 지진이 발생했습니다.</span><small>현수의 손을 잡고 400일 방으로</small>';document.body.append(el);}}
 act(event){const r=rescueTransition(this.getState(),event);if(!r.ok){this.sound.effect('error');this.toast(r.message);const el=$('#rescue-message');if(el)el.textContent=r.message;return false;}this.setState(r.state);this.world.rescueRuntime.sync(r.state);this.sound.effect(r.effect||'paper');this.toast(r.message);if(event.type==='next'&&r.state.quake)this.announce();return true;}
 interact(id){const s=this.getState();if(this.world.rescueRuntime.transition)return;
  if(id==='rescue-cabinet')return this.cabinet();
  if(id==='rescue-bed')return this.person('medicine',s.healed?'이제 조금 괜찮아졌어':'몸이 너무 아파…',s.healed?'약을 찾아줘서 고마워. 두 번째 문으로 가 보자.':'보관함 어딘가에 내 약을 넣어 둔 것 같은데…','현수에게 약 먹여 주기',s.healed);
  if(id==='rescue-rack')return this.wardrobe();if(id==='rescue-cashier')return this.checkout();
  if(id==='rescue-cold')return this.person('clothes',s.warmed?'이제 따뜻해!':'하영아, 너무 추워…',s.warmed?'내가 좋아하는 옷을 기억해 줬구나. ♡':'나시 하나로 겨울을 버티기는 힘들어. 나한테 어울리는 두 벌을 사 줄래?','현수에게 쇼핑백 건네기',s.warmed);
  if(id==='rescue-map')return this.map();
  if(id==='rescue-hungry')return this.person('propose',s.fed?'그 식당 맞아!':'너는 내가 어떤 식당을 가고 싶은지도 모르는구나....',s.fed?'텍사스 데 브라질. 고기 먹으러 같이 나가자!':'벽의 세계지도와 두 개의 핀으로 내 마음을 맞혀 봐.','완성한 이름판 제안하기',s.fed);
  if(id==='rescue-hand'){if(this.act({type:'hold'})){this.world.toggleView(true);this.closeModal();}return;}
  if(id.startsWith('rescue-door-')){const index=+id.split('-').at(-1);if(index!==s.room)return;if(this.act({type:index===3?'escape':'next'})){this.closeModal();this.world.active=false;if(index===3){this.audio.pause();$('#rescue-alert').hidden=true;}}return;}
  if(id==='rescue-finish')this.finish();
 }
 person(type,title,copy,button,done){this.showModal('rescue-person','201 — 300 · SAVE HYUNSU',title,`<div class="rescue-note">${esc(copy)}</div>${done?'<div class="rescue-stamp">구출 완료 ✓</div>':`<button id="rescue-give" class="primary">${button}</button>`}<p id="rescue-message" role="status"></p>`);if($('#rescue-give'))$('#rescue-give').onclick=()=>{if(this.act({type})){this.closeModal();if(type==='clothes'&&this.getState().warmed)this.subtitle('“이제 따뜻해! 역시 하영이가 골라 주는 옷이 최고야.”',6000);if(type==='medicine')this.subtitle('“약 찾아줘서 고마워. 이제 조금 살 것 같아.”',6000);}};}
 cabinet(){const s=this.getState();this.showModal('rescue-cabinet','01 · THE TROPHY CABINET',s.cabinetOpen?'대상 트로피가 가득한 보관함':'묵직한 보관함의 문',`<div class="rescue-cabinet-card"><span class="cabinet-emblem">大賞</span><p>${s.cabinetOpen?'대상, 대상, 또 대상…<br>여섯 개의 트로피가 빈틈없이 포진해 있다.':'수상 기록을 모아 둔 나무 보관함.<br>황동 손잡이를 당기면 열릴 것 같다.'}</p></div><button id="rescue-search" class="primary" ${s.healed||s.medicine?'disabled':''}>${s.medicine||s.healed?'약을 이미 챙겼어':s.cabinetOpen?'트로피 사이 뒤지기':'보관함 문 열기'}</button><p id="rescue-message" role="status">${s.medicine?'침대에 누운 현수에게 가져가 줘.':''}</p>`);$('#rescue-search').onclick=()=>{if(this.act({type:s.cabinetOpen?'search':'open-cabinet'})){if(s.cabinetOpen)this.closeModal();else this.cabinet();}};}
 wardrobe(){const rt=this.world.rescueRuntime,s=this.getState();this.showModal('rescue-shop','02 · THE WINTER EDIT','현수에게 어울리는 두 벌',`<p class="rescue-lead">기억 속 그날 입었던 옷을 찾아 줘. 두 벌을 고른 뒤 계산대 직원에게 가져가면 돼.</p><div class="rescue-basket"><b id="rescue-count"></b><span id="rescue-selected"></span><button id="rescue-leave-shop" class="secondary">계산대로 가기</button></div><div class="rescue-catalog">${rt.garments.map((g,i)=>`<button class="rescue-product" data-garment="${g.id}" aria-pressed="${s.selected.includes(g.id)}" ${s.warmed?'disabled':''}><span class="product-number">${String(i+1).padStart(2,'0')}</span><img src="${g.photo}" alt="${esc(g.name)}" loading="lazy"><span class="product-copy"><small>${esc(g.brand||'WINTER WARDROBE')}</small><b>${esc(g.name)}</b><span>${esc(g.detail||'진열 상품 · 선택해서 자세히 보기')}</span></span><i aria-hidden="true">✓</i></button>`).join('')}</div><p id="rescue-message" role="status"></p>`);
  const draw=()=>{const s=this.getState();$('#rescue-count').textContent=`선택한 옷 ${s.selected.length} / 2`;$('#rescue-selected').textContent=s.selected.map(id=>rt.garments.find(g=>g.id===id)?.name).join(' + ');$$('[data-garment]').forEach(b=>b.setAttribute('aria-pressed',s.selected.includes(b.dataset.garment)));};draw();$$('[data-garment]').forEach(b=>b.onclick=()=>{if(this.act({type:'select',id:b.dataset.garment,validIds:rt.garments.map(g=>g.id)}))draw();});$('#rescue-leave-shop').onclick=()=>{this.closeModal();this.toast('판매 직원이 서 있는 계산대로 걸어가 E를 눌러 줘.');};
 }
 checkout(){const s=this.getState(),items=s.selected.map(id=>this.world.rescueRuntime.garments.find(g=>g.id===id)).filter(Boolean);this.showModal('rescue-checkout','THE WINTER EDIT · CASH DESK',s.paid.length?'쇼핑백을 준비했어요':'두 벌, 계산 도와드릴게요',`<div class="rescue-receipt"><small>HAYOUNG’S WINTER GIFT</small>${items.map(g=>`<div><img src="${g.photo}" alt="${esc(g.name)}"><span>${esc(g.name)}</span><b>1</b></div>`).join('')||'<p>선택한 옷이 없어요.</p>'}<footer>총 ${items.length}벌 <strong>${s.paid.length?'PAID ✓':'READY TO WRAP'}</strong></footer><p>게임 안에서 진행되는 결제예요.</p></div><button id="rescue-pay" class="primary" ${s.paid.length||s.warmed?'disabled':''}>두 벌 건네고 결제하기</button><button id="rescue-checkout-leave" class="secondary">현수에게 돌아가기</button><p id="rescue-message" role="status"></p>`);$('#rescue-pay').onclick=()=>{if(this.act({type:'pay'}))this.checkout();};$('#rescue-checkout-leave').onclick=()=>this.closeModal();}
 map(){const rt=this.world.rescueRuntime;this.showModal('rescue-map','03 · TWO PLACES, ONE TABLE','어디로 먹으러 갈까?',`<p class="rescue-lead">파란 핀은 첫 번째 장소, 빨간 핀은 두 번째 장소. 핀을 고르고 지도 위의 위치를 눌러 줘.</p><div class="rescue-map-tools"><button data-pin="blue" class="pin-tool blue" aria-pressed="${this.color==='blue'}">파란 핀 · 첫 번째</button><button data-pin="red" class="pin-tool red" aria-pressed="${this.color==='red'}">빨간 핀 · 두 번째</button><button id="map-zoom" class="secondary">지도 확대</button></div><div class="rescue-map-scroll"><div id="rescue-map-surface" tabindex="0" role="application" aria-label="세계지도. 방향키로 십자선을 움직이고 Enter로 선택한 핀을 놓으세요."><img src="/assets/rescue/world-map.svg" alt="국가와 미국 주 경계가 표시된 세계지도" draggable="false"><span id="map-key-cursor" hidden>+</span><div id="map-pins"></div></div></div><p class="rescue-map-help">방향키로 위치 조절 · Enter로 핀 놓기 · 확대하면 미국의 주 경계를 더 자세히 볼 수 있어.</p><div class="rescue-answer"><span id="map-blue">(　)</span><b>vs</b><span id="map-red">(　)</span></div><div class="modal-actions"><button id="rescue-board" class="primary">이름판 완성해서 가져가기</button></div><p id="rescue-message" role="status"></p>`);
  const draw=()=>{const s=this.getState();$('#map-pins').innerHTML=['blue','red'].map(color=>{const p=s.pins[color];return p?`<span class="map-pin ${color}" style="left:${(p.lon+180)/3.6}%;top:${(90-p.lat)/1.8}%" aria-label="${color==='blue'?'파란':'빨간'} 핀 ${esc(regionLabel(p.region))}">●</span>`:'';}).join('');$('#map-blue').textContent='( '+regionLabel(s.pins.blue?.region)+' )';$('#map-red').textContent='( '+regionLabel(s.pins.red?.region)+' )';};draw();
  $$('[data-pin]').forEach(b=>b.onclick=()=>{this.color=b.dataset.pin;$$('[data-pin]').forEach(b=>b.setAttribute('aria-pressed',b.dataset.pin===this.color));});let cursor={x:.5,y:.5};const place=(x,y)=>{const lon=x*360-180,lat=90-y*180;if(this.act({type:'pin',color:this.color,lon,lat,region:regionAt(rt.regions,lon,lat)}))draw();};const surface=$('#rescue-map-surface');surface.onclick=e=>{if(this.getState().fed)return;const r=surface.getBoundingClientRect();cursor={x:(e.clientX-r.left)/r.width,y:(e.clientY-r.top)/r.height};place(cursor.x,cursor.y);};surface.onkeydown=e=>{if(!['ArrowLeft','ArrowRight','ArrowUp','ArrowDown','Enter'].includes(e.key))return;e.preventDefault();e.stopPropagation();if(e.key==='Enter')place(cursor.x,cursor.y);else{cursor.x=Math.max(0,Math.min(1,cursor.x+(e.key==='ArrowRight'?.005:e.key==='ArrowLeft'?-.005:0)));cursor.y=Math.max(0,Math.min(1,cursor.y+(e.key==='ArrowDown'?.005:e.key==='ArrowUp'?-.005:0)));const c=$('#map-key-cursor');c.hidden=false;c.style.left=cursor.x*100+'%';c.style.top=cursor.y*100+'%';}};$('#map-zoom').onclick=()=>{surface.classList.toggle('zoomed');$('#map-zoom').textContent=surface.classList.contains('zoomed')?'지도 축소':'지도 확대';};$('#rescue-board').onclick=()=>{if(this.act({type:'board'}))this.closeModal();};
 }
 announce(){this.alarmAt=this.world.rescueRuntime.elapsed;for(let i=0;i<6;i++)this.sound.tone(i%2?660:880,.18,.085,'sine',i*.2);this.audio.currentTime=0;this.audio.volume=this.sound.muted?0:this.sound.volume;this.audio.play().catch(()=>{if('speechSynthesis'in window){const u=new SpeechSynthesisUtterance('緊急地震速報。マグニチュード六点二の強い地震が発生しました。');u.lang='ja-JP';u.volume=this.sound.volume;speechSynthesis.speak(u);}});}
 tick(paused=false){const s=this.getState();$('#view-btn span').textContent=this.world.thirdPerson?'3인칭':'1인칭';$('#rescue-alert').hidden=s.room!==3||paused;this.audio.volume=this.sound.muted?0:this.sound.volume;if(paused){this.audio.pause();this.wasPaused=true;return;}if(this.wasPaused){this.wasPaused=false;if(s.room===3)this.audio.play().catch(()=>{});}if(s.room===3&&this.world.rescueRuntime.elapsed-this.alarmAt>18)this.announce();if(s.room!==3)this.audio.pause();}
 hint(){const s=this.getState();const hints=['병 이름을 천천히 읽어 봐. ‘대상’이 ‘포진’한 곳에 약을 숨겨 두었어. 보관함 문을 열고 트로피 사이를 뒤져 줘.','남색 폴로 니트 집업과 TOMBOY 코트를 떠올려 봐. 두 벌을 골라 계산한 뒤 현수에게 건네 줘.','미국 남부의 텍사스 주에 파란 핀, 남아메리카 브라질에 빨간 핀. 이름판을 챙겨 현수에게 제안해 줘.','먼저 현수 앞에서 E로 손을 잡아 줘. 함께 걷다가 400일 방의 문 앞에서 E를 누르면 돼.','우리는 함께 다음 기억에 도착했어.'];this.showModal('rescue-hint','SAVE HYUNSU · HINT','현수에게 물어보기',`<p class="body-copy">${rescueObjectives[s.room]}</p><details class="rescue-hint"><summary>한 단계 더 힌트 보기</summary><p>${hints[s.room]}</p></details>`);}
 finish(){this.showModal('rescue-complete','201 — 300 · ALL FOUR MEMORIES','현수를 구했다!',`<div class="rescue-stamp">4 / 4 ♡</div><p class="body-copy">아팠던 날, 추웠던 날, 배고팠던 날,<br>그리고 땅이 흔들리던 순간에도.<br><br>늘 손을 잡아 준 하영이 덕분에 무사히 도착했어.</p><div class="rescue-note">400일 방에 도착했어.<br>다음 이야기는 이곳에서 이어질 거야.</div><button id="rescue-rest" class="primary">도착한 방 둘러보기</button><button id="rescue-bonus" class="secondary">보너스 공주방으로</button>`);$('#rescue-rest').onclick=()=>this.closeModal();$('#rescue-bonus').onclick=this.onBonus;}
}
